-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Compiled.ScalarCodecs exposing (Id, NaiveDateTime, codecs)

import Api.Compiled.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Id =
    Api.Compiled.Scalar.Id


type alias NaiveDateTime =
    Api.Compiled.Scalar.NaiveDateTime


codecs : Api.Compiled.Scalar.Codecs Id NaiveDateTime
codecs =
    Api.Compiled.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        , codecNaiveDateTime = defaultCodecs.codecNaiveDateTime
        }
