-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Compiled.Object.CommitAuthor exposing (date, email, name)

import Api.Compiled.InputObject
import Api.Compiled.Interface
import Api.Compiled.Object
import Api.Compiled.Scalar
import Api.Compiled.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


date : SelectionSet Api.Compiled.Scalar.NaiveDateTime Api.Compiled.Object.CommitAuthor
date =
    Object.selectionForField "Scalar.NaiveDateTime" "date" [] (Object.scalarDecoder |> Decode.map Api.Compiled.Scalar.NaiveDateTime)


email : SelectionSet String Api.Compiled.Object.CommitAuthor
email =
    Object.selectionForField "String" "email" [] Decode.string


name : SelectionSet String Api.Compiled.Object.CommitAuthor
name =
    Object.selectionForField "String" "name" [] Decode.string
