-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Compiled.Object.KnownHost exposing (comment, entry, fingerprintMd5, fingerprintSha256, hosts, id)

import Api.Compiled.InputObject
import Api.Compiled.Interface
import Api.Compiled.Object
import Api.Compiled.Scalar
import Api.Compiled.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


comment : SelectionSet String Api.Compiled.Object.KnownHost
comment =
    Object.selectionForField "String" "comment" [] Decode.string


entry : SelectionSet String Api.Compiled.Object.KnownHost
entry =
    Object.selectionForField "String" "entry" [] Decode.string


fingerprintMd5 : SelectionSet String Api.Compiled.Object.KnownHost
fingerprintMd5 =
    Object.selectionForField "String" "fingerprintMd5" [] Decode.string


fingerprintSha256 : SelectionSet String Api.Compiled.Object.KnownHost
fingerprintSha256 =
    Object.selectionForField "String" "fingerprintSha256" [] Decode.string


hosts : SelectionSet String Api.Compiled.Object.KnownHost
hosts =
    Object.selectionForField "String" "hosts" [] Decode.string


id : SelectionSet Api.Compiled.Scalar.Id Api.Compiled.Object.KnownHost
id =
    Object.selectionForField "Scalar.Id" "id" [] (Object.scalarDecoder |> Decode.map Api.Compiled.Scalar.Id)
