-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Compiled.Object.Project exposing (address, branches, id, insertedAt, name, slug, updatedAt)

import Api.Compiled.InputObject
import Api.Compiled.Interface
import Api.Compiled.Object
import Api.Compiled.Scalar
import Api.Compiled.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


address : SelectionSet String Api.Compiled.Object.Project
address =
    Object.selectionForField "String" "address" [] Decode.string


branches : SelectionSet decodesTo Api.Compiled.Object.Branch -> SelectionSet (List decodesTo) Api.Compiled.Object.Project
branches object_ =
    Object.selectionForCompositeField "branches" [] object_ (identity >> Decode.list)


id : SelectionSet Api.Compiled.Scalar.Id Api.Compiled.Object.Project
id =
    Object.selectionForField "Scalar.Id" "id" [] (Object.scalarDecoder |> Decode.map Api.Compiled.Scalar.Id)


insertedAt : SelectionSet Api.Compiled.Scalar.NaiveDateTime Api.Compiled.Object.Project
insertedAt =
    Object.selectionForField "Scalar.NaiveDateTime" "insertedAt" [] (Object.scalarDecoder |> Decode.map Api.Compiled.Scalar.NaiveDateTime)


name : SelectionSet String Api.Compiled.Object.Project
name =
    Object.selectionForField "String" "name" [] Decode.string


slug : SelectionSet String Api.Compiled.Object.Project
slug =
    Object.selectionForField "String" "slug" [] Decode.string


updatedAt : SelectionSet Api.Compiled.Scalar.NaiveDateTime Api.Compiled.Object.Project
updatedAt =
    Object.selectionForField "Scalar.NaiveDateTime" "updatedAt" [] (Object.scalarDecoder |> Decode.map Api.Compiled.Scalar.NaiveDateTime)
