-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Compiled.Object.ProjectPayload exposing (messages, result, successful)

import Api.Compiled.InputObject
import Api.Compiled.Interface
import Api.Compiled.Object
import Api.Compiled.Scalar
import Api.Compiled.ScalarCodecs
import Api.Compiled.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| A list of failed validations. May be blank or null if mutation succeeded.
-}
messages : SelectionSet decodesTo Api.Compiled.Object.ValidationMessage -> SelectionSet (Maybe (List (Maybe decodesTo))) Api.Compiled.Object.ProjectPayload
messages object_ =
    Object.selectionForCompositeField "messages" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| The object created/updated/deleted by the mutation. May be null if mutation failed.
-}
result : SelectionSet decodesTo Api.Compiled.Object.Project -> SelectionSet (Maybe decodesTo) Api.Compiled.Object.ProjectPayload
result object_ =
    Object.selectionForCompositeField "result" [] object_ (identity >> Decode.nullable)


{-| Indicates if the mutation completed successfully or not.
-}
successful : SelectionSet Bool Api.Compiled.Object.ProjectPayload
successful =
    Object.selectionForField "Bool" "successful" [] Decode.bool
