-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Compiled.Object.ProjectConnection exposing (edges, pageInfo)

import Api.Compiled.InputObject
import Api.Compiled.Interface
import Api.Compiled.Object
import Api.Compiled.Scalar
import Api.Compiled.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


edges : SelectionSet decodesTo Api.Compiled.Object.ProjectEdge -> SelectionSet (Maybe (List (Maybe decodesTo))) Api.Compiled.Object.ProjectConnection
edges object_ =
    Object.selectionForCompositeField "edges" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


pageInfo : SelectionSet decodesTo Api.Compiled.Object.PageInfo -> SelectionSet decodesTo Api.Compiled.Object.ProjectConnection
pageInfo object_ =
    Object.selectionForCompositeField "pageInfo" [] object_ identity
