-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Compiled.Object.User exposing (id, username)

import Api.Compiled.InputObject
import Api.Compiled.Interface
import Api.Compiled.Object
import Api.Compiled.Scalar
import Api.Compiled.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet (Maybe Api.Compiled.Scalar.Id) Api.Compiled.Object.User
id =
    Object.selectionForField "(Maybe Scalar.Id)" "id" [] (Object.scalarDecoder |> Decode.map Api.Compiled.Scalar.Id |> Decode.nullable)


username : SelectionSet String Api.Compiled.Object.User
username =
    Object.selectionForField "String" "username" [] Decode.string
