-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Compiled.Object exposing (Branch(..), Commit(..), CommitAuthor(..), KnownHost(..), KnownHostPayload(..), Project(..), ProjectPayload(..), Session(..), SessionPayload(..), ValidationMessage(..), ValidationOption(..))


type Branch
    = Branch


type Commit
    = Commit


type CommitAuthor
    = CommitAuthor


type KnownHost
    = KnownHost


type KnownHostPayload
    = KnownHostPayload


type Project
    = Project


type ProjectPayload
    = ProjectPayload


type Session
    = Session


type SessionPayload
    = SessionPayload


type ValidationMessage
    = ValidationMessage


type ValidationOption
    = ValidationOption
