-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Compiled.Object exposing (KnownHost(..), Project(..), Session(..), SessionPayload(..), User(..), UserPayload(..), ValidationMessage(..), ValidationOption(..))


type KnownHost
    = KnownHost


type Project
    = Project


type Session
    = Session


type SessionPayload
    = SessionPayload


type User
    = User


type UserPayload
    = UserPayload


type ValidationMessage
    = ValidationMessage


type ValidationOption
    = ValidationOption
