// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PageQuery struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Skip                 int32    `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageQuery) Reset()         { *m = PageQuery{} }
func (m *PageQuery) String() string { return proto.CompactTextString(m) }
func (*PageQuery) ProtoMessage()    {}
func (*PageQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *PageQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageQuery.Unmarshal(m, b)
}
func (m *PageQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageQuery.Marshal(b, m, deterministic)
}
func (m *PageQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageQuery.Merge(m, src)
}
func (m *PageQuery) XXX_Size() int {
	return xxx_messageInfo_PageQuery.Size(m)
}
func (m *PageQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_PageQuery.DiscardUnknown(m)
}

var xxx_messageInfo_PageQuery proto.InternalMessageInfo

func (m *PageQuery) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *PageQuery) GetSkip() int32 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func init() {
	proto.RegisterType((*PageQuery)(nil), "velocity.v1.PageQuery")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 104 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2e, 0x4b, 0xcd, 0xc9, 0x4f, 0xce, 0x2c, 0xa9, 0xd4,
	0x2b, 0x33, 0x54, 0x32, 0xe5, 0xe2, 0x0c, 0x48, 0x4c, 0x4f, 0x0d, 0x2c, 0x4d, 0x2d, 0xaa, 0x14,
	0x12, 0xe1, 0x62, 0xcd, 0xc9, 0xcc, 0xcd, 0x2c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x82,
	0x70, 0x84, 0x84, 0xb8, 0x58, 0x8a, 0xb3, 0x33, 0x0b, 0x24, 0x98, 0xc0, 0x82, 0x60, 0xb6, 0x13,
	0x4b, 0x14, 0x53, 0x99, 0x61, 0x12, 0x1b, 0xd8, 0x40, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xf8, 0xfe, 0xe9, 0xd5, 0x5d, 0x00, 0x00, 0x00,
}
