// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blueprint.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Blueprint struct {
	// BLUEPRINT_ID = commit_sha+blueprint_name
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId            string       `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	CommitId             string       `protobuf:"bytes,3,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	Name                 string       `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description          string       `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Parameters           []*Parameter `protobuf:"bytes,6,rep,name=parameters,proto3" json:"parameters,omitempty"`
	Steps                []*Step      `protobuf:"bytes,7,rep,name=steps,proto3" json:"steps,omitempty"`
	Docker               *Docker      `protobuf:"bytes,8,opt,name=docker,proto3" json:"docker,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Blueprint) Reset()         { *m = Blueprint{} }
func (m *Blueprint) String() string { return proto.CompactTextString(m) }
func (*Blueprint) ProtoMessage()    {}
func (*Blueprint) Descriptor() ([]byte, []int) {
	return fileDescriptor_d334b799e628a382, []int{0}
}

func (m *Blueprint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blueprint.Unmarshal(m, b)
}
func (m *Blueprint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blueprint.Marshal(b, m, deterministic)
}
func (m *Blueprint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blueprint.Merge(m, src)
}
func (m *Blueprint) XXX_Size() int {
	return xxx_messageInfo_Blueprint.Size(m)
}
func (m *Blueprint) XXX_DiscardUnknown() {
	xxx_messageInfo_Blueprint.DiscardUnknown(m)
}

var xxx_messageInfo_Blueprint proto.InternalMessageInfo

func (m *Blueprint) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Blueprint) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *Blueprint) GetCommitId() string {
	if m != nil {
		return m.CommitId
	}
	return ""
}

func (m *Blueprint) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Blueprint) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Blueprint) GetParameters() []*Parameter {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *Blueprint) GetSteps() []*Step {
	if m != nil {
		return m.Steps
	}
	return nil
}

func (m *Blueprint) GetDocker() *Docker {
	if m != nil {
		return m.Docker
	}
	return nil
}

type Parameter struct {
	Secret bool `protobuf:"varint,1,opt,name=secret,proto3" json:"secret,omitempty"`
	// Types that are valid to be assigned to Impl:
	//	*Parameter_BasicParameter
	//	*Parameter_DerivedParameter
	Impl                 isParameter_Impl `protobuf_oneof:"impl"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Parameter) Reset()         { *m = Parameter{} }
func (m *Parameter) String() string { return proto.CompactTextString(m) }
func (*Parameter) ProtoMessage()    {}
func (*Parameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_d334b799e628a382, []int{1}
}

func (m *Parameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parameter.Unmarshal(m, b)
}
func (m *Parameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parameter.Marshal(b, m, deterministic)
}
func (m *Parameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parameter.Merge(m, src)
}
func (m *Parameter) XXX_Size() int {
	return xxx_messageInfo_Parameter.Size(m)
}
func (m *Parameter) XXX_DiscardUnknown() {
	xxx_messageInfo_Parameter.DiscardUnknown(m)
}

var xxx_messageInfo_Parameter proto.InternalMessageInfo

func (m *Parameter) GetSecret() bool {
	if m != nil {
		return m.Secret
	}
	return false
}

type isParameter_Impl interface {
	isParameter_Impl()
}

type Parameter_BasicParameter struct {
	BasicParameter *BasicParameter `protobuf:"bytes,11,opt,name=basic_parameter,json=basicParameter,proto3,oneof"`
}

type Parameter_DerivedParameter struct {
	DerivedParameter *DerivedParameter `protobuf:"bytes,12,opt,name=derived_parameter,json=derivedParameter,proto3,oneof"`
}

func (*Parameter_BasicParameter) isParameter_Impl() {}

func (*Parameter_DerivedParameter) isParameter_Impl() {}

func (m *Parameter) GetImpl() isParameter_Impl {
	if m != nil {
		return m.Impl
	}
	return nil
}

func (m *Parameter) GetBasicParameter() *BasicParameter {
	if x, ok := m.GetImpl().(*Parameter_BasicParameter); ok {
		return x.BasicParameter
	}
	return nil
}

func (m *Parameter) GetDerivedParameter() *DerivedParameter {
	if x, ok := m.GetImpl().(*Parameter_DerivedParameter); ok {
		return x.DerivedParameter
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Parameter) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Parameter_BasicParameter)(nil),
		(*Parameter_DerivedParameter)(nil),
	}
}

type BasicParameter struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Default              string   `protobuf:"bytes,2,opt,name=default,proto3" json:"default,omitempty"`
	Choices              []string `protobuf:"bytes,3,rep,name=choices,proto3" json:"choices,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BasicParameter) Reset()         { *m = BasicParameter{} }
func (m *BasicParameter) String() string { return proto.CompactTextString(m) }
func (*BasicParameter) ProtoMessage()    {}
func (*BasicParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_d334b799e628a382, []int{2}
}

func (m *BasicParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasicParameter.Unmarshal(m, b)
}
func (m *BasicParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasicParameter.Marshal(b, m, deterministic)
}
func (m *BasicParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicParameter.Merge(m, src)
}
func (m *BasicParameter) XXX_Size() int {
	return xxx_messageInfo_BasicParameter.Size(m)
}
func (m *BasicParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicParameter.DiscardUnknown(m)
}

var xxx_messageInfo_BasicParameter proto.InternalMessageInfo

func (m *BasicParameter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BasicParameter) GetDefault() string {
	if m != nil {
		return m.Default
	}
	return ""
}

func (m *BasicParameter) GetChoices() []string {
	if m != nil {
		return m.Choices
	}
	return nil
}

type DerivedParameter struct {
	Use                  string            `protobuf:"bytes,1,opt,name=use,proto3" json:"use,omitempty"`
	Arguments            map[string]string `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Exports              map[string]string `protobuf:"bytes,3,rep,name=exports,proto3" json:"exports,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DerivedParameter) Reset()         { *m = DerivedParameter{} }
func (m *DerivedParameter) String() string { return proto.CompactTextString(m) }
func (*DerivedParameter) ProtoMessage()    {}
func (*DerivedParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_d334b799e628a382, []int{3}
}

func (m *DerivedParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DerivedParameter.Unmarshal(m, b)
}
func (m *DerivedParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DerivedParameter.Marshal(b, m, deterministic)
}
func (m *DerivedParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DerivedParameter.Merge(m, src)
}
func (m *DerivedParameter) XXX_Size() int {
	return xxx_messageInfo_DerivedParameter.Size(m)
}
func (m *DerivedParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_DerivedParameter.DiscardUnknown(m)
}

var xxx_messageInfo_DerivedParameter proto.InternalMessageInfo

func (m *DerivedParameter) GetUse() string {
	if m != nil {
		return m.Use
	}
	return ""
}

func (m *DerivedParameter) GetArguments() map[string]string {
	if m != nil {
		return m.Arguments
	}
	return nil
}

func (m *DerivedParameter) GetExports() map[string]string {
	if m != nil {
		return m.Exports
	}
	return nil
}

type Docker struct {
	Registries           []*DockerRegistry `protobuf:"bytes,1,rep,name=registries,proto3" json:"registries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Docker) Reset()         { *m = Docker{} }
func (m *Docker) String() string { return proto.CompactTextString(m) }
func (*Docker) ProtoMessage()    {}
func (*Docker) Descriptor() ([]byte, []int) {
	return fileDescriptor_d334b799e628a382, []int{4}
}

func (m *Docker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Docker.Unmarshal(m, b)
}
func (m *Docker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Docker.Marshal(b, m, deterministic)
}
func (m *Docker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Docker.Merge(m, src)
}
func (m *Docker) XXX_Size() int {
	return xxx_messageInfo_Docker.Size(m)
}
func (m *Docker) XXX_DiscardUnknown() {
	xxx_messageInfo_Docker.DiscardUnknown(m)
}

var xxx_messageInfo_Docker proto.InternalMessageInfo

func (m *Docker) GetRegistries() []*DockerRegistry {
	if m != nil {
		return m.Registries
	}
	return nil
}

type DockerRegistry struct {
	Address              string            `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Use                  string            `protobuf:"bytes,2,opt,name=use,proto3" json:"use,omitempty"`
	Arguments            map[string]string `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DockerRegistry) Reset()         { *m = DockerRegistry{} }
func (m *DockerRegistry) String() string { return proto.CompactTextString(m) }
func (*DockerRegistry) ProtoMessage()    {}
func (*DockerRegistry) Descriptor() ([]byte, []int) {
	return fileDescriptor_d334b799e628a382, []int{5}
}

func (m *DockerRegistry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DockerRegistry.Unmarshal(m, b)
}
func (m *DockerRegistry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DockerRegistry.Marshal(b, m, deterministic)
}
func (m *DockerRegistry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DockerRegistry.Merge(m, src)
}
func (m *DockerRegistry) XXX_Size() int {
	return xxx_messageInfo_DockerRegistry.Size(m)
}
func (m *DockerRegistry) XXX_DiscardUnknown() {
	xxx_messageInfo_DockerRegistry.DiscardUnknown(m)
}

var xxx_messageInfo_DockerRegistry proto.InternalMessageInfo

func (m *DockerRegistry) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *DockerRegistry) GetUse() string {
	if m != nil {
		return m.Use
	}
	return ""
}

func (m *DockerRegistry) GetArguments() map[string]string {
	if m != nil {
		return m.Arguments
	}
	return nil
}

type GetBlueprintRequest struct {
	// The id of the project in the form of
	// `[PROJECT_ID]`.
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// The id of the blueprint in the form of
	// `[BLUEPRINT_ID]`.
	BlueprintId          string   `protobuf:"bytes,2,opt,name=blueprint_id,json=blueprintId,proto3" json:"blueprint_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlueprintRequest) Reset()         { *m = GetBlueprintRequest{} }
func (m *GetBlueprintRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlueprintRequest) ProtoMessage()    {}
func (*GetBlueprintRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d334b799e628a382, []int{6}
}

func (m *GetBlueprintRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlueprintRequest.Unmarshal(m, b)
}
func (m *GetBlueprintRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlueprintRequest.Marshal(b, m, deterministic)
}
func (m *GetBlueprintRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlueprintRequest.Merge(m, src)
}
func (m *GetBlueprintRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlueprintRequest.Size(m)
}
func (m *GetBlueprintRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlueprintRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlueprintRequest proto.InternalMessageInfo

func (m *GetBlueprintRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *GetBlueprintRequest) GetBlueprintId() string {
	if m != nil {
		return m.BlueprintId
	}
	return ""
}

type ListBlueprintsRequest struct {
	RepoQuery            *RepoQuery `protobuf:"bytes,1,opt,name=repo_query,json=repoQuery,proto3" json:"repo_query,omitempty"`
	PageQuery            *PageQuery `protobuf:"bytes,99,opt,name=page_query,json=pageQuery,proto3" json:"page_query,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListBlueprintsRequest) Reset()         { *m = ListBlueprintsRequest{} }
func (m *ListBlueprintsRequest) String() string { return proto.CompactTextString(m) }
func (*ListBlueprintsRequest) ProtoMessage()    {}
func (*ListBlueprintsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d334b799e628a382, []int{7}
}

func (m *ListBlueprintsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBlueprintsRequest.Unmarshal(m, b)
}
func (m *ListBlueprintsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBlueprintsRequest.Marshal(b, m, deterministic)
}
func (m *ListBlueprintsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBlueprintsRequest.Merge(m, src)
}
func (m *ListBlueprintsRequest) XXX_Size() int {
	return xxx_messageInfo_ListBlueprintsRequest.Size(m)
}
func (m *ListBlueprintsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBlueprintsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBlueprintsRequest proto.InternalMessageInfo

func (m *ListBlueprintsRequest) GetRepoQuery() *RepoQuery {
	if m != nil {
		return m.RepoQuery
	}
	return nil
}

func (m *ListBlueprintsRequest) GetPageQuery() *PageQuery {
	if m != nil {
		return m.PageQuery
	}
	return nil
}

type ListBlueprintsResponse struct {
	Blueprints           []*Blueprint `protobuf:"bytes,1,rep,name=blueprints,proto3" json:"blueprints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListBlueprintsResponse) Reset()         { *m = ListBlueprintsResponse{} }
func (m *ListBlueprintsResponse) String() string { return proto.CompactTextString(m) }
func (*ListBlueprintsResponse) ProtoMessage()    {}
func (*ListBlueprintsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d334b799e628a382, []int{8}
}

func (m *ListBlueprintsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBlueprintsResponse.Unmarshal(m, b)
}
func (m *ListBlueprintsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBlueprintsResponse.Marshal(b, m, deterministic)
}
func (m *ListBlueprintsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBlueprintsResponse.Merge(m, src)
}
func (m *ListBlueprintsResponse) XXX_Size() int {
	return xxx_messageInfo_ListBlueprintsResponse.Size(m)
}
func (m *ListBlueprintsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBlueprintsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBlueprintsResponse proto.InternalMessageInfo

func (m *ListBlueprintsResponse) GetBlueprints() []*Blueprint {
	if m != nil {
		return m.Blueprints
	}
	return nil
}

func init() {
	proto.RegisterType((*Blueprint)(nil), "velocity.v1.Blueprint")
	proto.RegisterType((*Parameter)(nil), "velocity.v1.Parameter")
	proto.RegisterType((*BasicParameter)(nil), "velocity.v1.BasicParameter")
	proto.RegisterType((*DerivedParameter)(nil), "velocity.v1.DerivedParameter")
	proto.RegisterMapType((map[string]string)(nil), "velocity.v1.DerivedParameter.ArgumentsEntry")
	proto.RegisterMapType((map[string]string)(nil), "velocity.v1.DerivedParameter.ExportsEntry")
	proto.RegisterType((*Docker)(nil), "velocity.v1.Docker")
	proto.RegisterType((*DockerRegistry)(nil), "velocity.v1.DockerRegistry")
	proto.RegisterMapType((map[string]string)(nil), "velocity.v1.DockerRegistry.ArgumentsEntry")
	proto.RegisterType((*GetBlueprintRequest)(nil), "velocity.v1.GetBlueprintRequest")
	proto.RegisterType((*ListBlueprintsRequest)(nil), "velocity.v1.ListBlueprintsRequest")
	proto.RegisterType((*ListBlueprintsResponse)(nil), "velocity.v1.ListBlueprintsResponse")
}

func init() { proto.RegisterFile("blueprint.proto", fileDescriptor_d334b799e628a382) }

var fileDescriptor_d334b799e628a382 = []byte{
	// 763 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x4e, 0x9a, 0xd6, 0x93, 0x28, 0x4d, 0xb7, 0x50, 0x59, 0x29, 0x95, 0x82, 0x41, 0x22,
	0x0a, 0x28, 0x51, 0x83, 0x40, 0xa8, 0xc0, 0x81, 0xa8, 0x85, 0x16, 0xf5, 0x50, 0xdc, 0x03, 0x88,
	0x4b, 0xe5, 0xd8, 0x43, 0x58, 0x9a, 0x78, 0xb7, 0xbb, 0x9b, 0x88, 0x08, 0xf5, 0x02, 0xe2, 0xca,
	0x85, 0x23, 0x2f, 0xc1, 0x2b, 0x20, 0xf1, 0x06, 0xbc, 0x02, 0x0f, 0x82, 0xfc, 0x1b, 0x3b, 0x4a,
	0x2b, 0x21, 0x6e, 0xbb, 0xf3, 0xcd, 0x7c, 0xfb, 0xcd, 0x7c, 0xd6, 0x18, 0x56, 0xfb, 0xc3, 0x31,
	0x72, 0x41, 0x7d, 0xd5, 0xe6, 0x82, 0x29, 0x46, 0xca, 0x13, 0x1c, 0x32, 0x97, 0xaa, 0x69, 0x7b,
	0xb2, 0x5d, 0x37, 0x1c, 0x4e, 0xa3, 0x78, 0xbd, 0x26, 0x90, 0x33, 0x49, 0x15, 0x13, 0xd3, 0x38,
	0x02, 0x52, 0x21, 0x8f, 0xcf, 0xd7, 0x07, 0x8c, 0x0d, 0x86, 0xd8, 0x71, 0x38, 0xed, 0x38, 0xbe,
	0xcf, 0x94, 0xa3, 0x28, 0xf3, 0x65, 0x84, 0x5a, 0xdf, 0x75, 0x30, 0x7a, 0xc9, 0x3b, 0xa4, 0x0a,
	0x3a, 0xf5, 0x4c, 0xad, 0xa1, 0x35, 0x0d, 0x5b, 0xa7, 0x1e, 0xd9, 0x02, 0xe0, 0x82, 0xbd, 0x47,
	0x57, 0x9d, 0x50, 0xcf, 0xd4, 0xc3, 0xb8, 0x11, 0x47, 0x0e, 0x3c, 0xb2, 0x09, 0x86, 0xcb, 0x46,
	0x23, 0x1a, 0xa2, 0x85, 0x10, 0x5d, 0x89, 0x02, 0x07, 0x1e, 0x21, 0x50, 0xf4, 0x9d, 0x11, 0x9a,
	0xc5, 0x30, 0x1e, 0x9e, 0x49, 0x03, 0xca, 0x1e, 0x4a, 0x57, 0x50, 0x1e, 0x68, 0x30, 0x97, 0x42,
	0x28, 0x1b, 0x22, 0x0f, 0x00, 0xb8, 0x23, 0x9c, 0x11, 0x2a, 0x14, 0xd2, 0x2c, 0x35, 0x0a, 0xcd,
	0x72, 0x77, 0xa3, 0x9d, 0x69, 0xbc, 0x7d, 0x94, 0xc0, 0x76, 0x26, 0x93, 0xdc, 0x86, 0xa5, 0xa0,
	0x67, 0x69, 0x2e, 0x87, 0x25, 0x6b, 0xb9, 0x92, 0x63, 0x85, 0xdc, 0x8e, 0x70, 0x72, 0x07, 0x4a,
	0x1e, 0x73, 0x4f, 0x51, 0x98, 0x2b, 0x0d, 0xad, 0x59, 0xee, 0xae, 0xe7, 0x32, 0x77, 0x43, 0xc8,
	0x8e, 0x53, 0xac, 0x9f, 0x1a, 0x18, 0xe9, 0x7b, 0x64, 0x03, 0x4a, 0x12, 0x5d, 0x81, 0x2a, 0x9c,
	0xd0, 0x8a, 0x1d, 0xdf, 0xc8, 0x33, 0x58, 0xed, 0x3b, 0x92, 0xba, 0x27, 0xa9, 0x1e, 0xb3, 0x1c,
	0x72, 0x6f, 0xe6, 0xb8, 0x7b, 0x41, 0x4e, 0xca, 0xb6, 0x7f, 0xc5, 0xae, 0xf6, 0x73, 0x11, 0x72,
	0x08, 0x6b, 0x1e, 0x0a, 0x3a, 0x41, 0x2f, 0xc3, 0x54, 0x09, 0x99, 0xb6, 0xf2, 0x2a, 0xa3, 0xac,
	0x2c, 0x57, 0xcd, 0x9b, 0x8b, 0xf5, 0x4a, 0x50, 0xa4, 0x23, 0x3e, 0xb4, 0x5e, 0x43, 0x35, 0xff,
	0x72, 0xea, 0x8c, 0x96, 0x71, 0xc6, 0x84, 0x65, 0x0f, 0xdf, 0x3a, 0xe3, 0xa1, 0x8a, 0x6d, 0x4e,
	0xae, 0x01, 0xe2, 0xbe, 0x63, 0xd4, 0x45, 0x69, 0x16, 0x1a, 0x85, 0x00, 0x89, 0xaf, 0xd6, 0x0f,
	0x1d, 0x6a, 0xf3, 0x52, 0x48, 0x0d, 0x0a, 0x63, 0x99, 0x70, 0x07, 0x47, 0xf2, 0x02, 0x0c, 0x47,
	0x0c, 0xc6, 0x23, 0xf4, 0x95, 0x34, 0xf5, 0xd0, 0x9e, 0xbb, 0x97, 0xb6, 0xd3, 0x7e, 0x9a, 0xa4,
	0xef, 0xf9, 0x4a, 0x4c, 0xed, 0x59, 0x39, 0xd9, 0x85, 0x65, 0xfc, 0xc0, 0x99, 0x50, 0x91, 0x98,
	0x72, 0xb7, 0x75, 0x39, 0xd3, 0x5e, 0x94, 0x1c, 0xf1, 0x24, 0xa5, 0xf5, 0xc7, 0x50, 0xcd, 0x3f,
	0x11, 0xa8, 0x3e, 0xc5, 0x69, 0xa2, 0xfa, 0x14, 0xa7, 0xe4, 0x2a, 0x2c, 0x4d, 0x9c, 0xe1, 0x18,
	0xe3, 0x71, 0x44, 0x97, 0x1d, 0xfd, 0xa1, 0x56, 0xdf, 0x81, 0x4a, 0x96, 0xf6, 0x5f, 0x6a, 0xad,
	0x3d, 0x28, 0x45, 0x9f, 0x18, 0x79, 0x04, 0x20, 0x70, 0x40, 0xa5, 0x12, 0x14, 0xa5, 0xa9, 0x85,
	0xcd, 0x6c, 0x2e, 0xfa, 0x16, 0xa3, 0xa4, 0xa9, 0x9d, 0x49, 0xb7, 0x7e, 0x69, 0x50, 0xcd, 0xc3,
	0x81, 0x4d, 0x8e, 0xe7, 0x09, 0x94, 0x32, 0x56, 0x92, 0x5c, 0x13, 0x47, 0xf4, 0x99, 0x23, 0xfb,
	0x59, 0x47, 0x16, 0xce, 0x31, 0xc7, 0x7d, 0xb1, 0x1f, 0xff, 0x37, 0x49, 0xeb, 0x15, 0xac, 0x3f,
	0x47, 0x95, 0xae, 0x1f, 0x1b, 0xcf, 0xc6, 0x28, 0xd5, 0xdc, 0xd6, 0xd1, 0xe6, 0xb7, 0xce, 0x0d,
	0xa8, 0xa4, 0x9b, 0x71, 0xb6, 0x96, 0xca, 0x69, 0xec, 0xc0, 0xb3, 0xbe, 0x68, 0x70, 0xed, 0x90,
	0xca, 0x19, 0xb5, 0x4c, 0xb8, 0xef, 0x07, 0x63, 0xe7, 0xec, 0xe4, 0x6c, 0x8c, 0x22, 0x52, 0x39,
	0xbf, 0x5f, 0x6c, 0xe4, 0xec, 0x65, 0x80, 0xda, 0x86, 0x48, 0x8e, 0x41, 0x19, 0x77, 0x06, 0x18,
	0x97, 0xb9, 0x0b, 0xca, 0x8e, 0x9c, 0x01, 0xc6, 0x65, 0x3c, 0x39, 0x5a, 0x47, 0xb0, 0x31, 0x2f,
	0x43, 0x72, 0xe6, 0x4b, 0x0c, 0xf6, 0x5c, 0x2a, 0x38, 0xb1, 0x3f, 0x4f, 0x38, 0x1b, 0x4b, 0x26,
	0xb3, 0xfb, 0x55, 0x87, 0x5a, 0x8a, 0x1c, 0xa3, 0x98, 0x50, 0x17, 0x89, 0x82, 0x4a, 0x76, 0x8e,
	0xa4, 0x91, 0x23, 0x5a, 0x30, 0xe2, 0xfa, 0x05, 0x4f, 0x59, 0xad, 0x4f, 0xbf, 0xff, 0x7c, 0xd3,
	0x6f, 0x11, 0xab, 0x33, 0xd9, 0xee, 0x7c, 0x0c, 0x36, 0xc3, 0x93, 0x78, 0xf0, 0xb2, 0xd3, 0xea,
	0xcc, 0x74, 0x74, 0x5a, 0xe7, 0xe4, 0xb3, 0x06, 0xd5, 0x7c, 0x77, 0xc4, 0xca, 0xd1, 0x2e, 0x74,
	0xa0, 0x7e, 0xf3, 0xd2, 0x9c, 0x68, 0x3c, 0x56, 0x33, 0xd4, 0x61, 0x91, 0xc6, 0x22, 0x1d, 0xe7,
	0x19, 0x21, 0xbd, 0xe2, 0x1b, 0x7d, 0xb2, 0xdd, 0x2f, 0x85, 0x7f, 0xb3, 0x7b, 0x7f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x82, 0xa0, 0x9f, 0x42, 0x34, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BlueprintServiceClient is the client API for BlueprintService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlueprintServiceClient interface {
	GetBlueprint(ctx context.Context, in *GetBlueprintRequest, opts ...grpc.CallOption) (*Blueprint, error)
	ListBlueprints(ctx context.Context, in *ListBlueprintsRequest, opts ...grpc.CallOption) (*ListBlueprintsResponse, error)
}

type blueprintServiceClient struct {
	cc *grpc.ClientConn
}

func NewBlueprintServiceClient(cc *grpc.ClientConn) BlueprintServiceClient {
	return &blueprintServiceClient{cc}
}

func (c *blueprintServiceClient) GetBlueprint(ctx context.Context, in *GetBlueprintRequest, opts ...grpc.CallOption) (*Blueprint, error) {
	out := new(Blueprint)
	err := c.cc.Invoke(ctx, "/velocity.v1.BlueprintService/GetBlueprint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blueprintServiceClient) ListBlueprints(ctx context.Context, in *ListBlueprintsRequest, opts ...grpc.CallOption) (*ListBlueprintsResponse, error) {
	out := new(ListBlueprintsResponse)
	err := c.cc.Invoke(ctx, "/velocity.v1.BlueprintService/ListBlueprints", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlueprintServiceServer is the server API for BlueprintService service.
type BlueprintServiceServer interface {
	GetBlueprint(context.Context, *GetBlueprintRequest) (*Blueprint, error)
	ListBlueprints(context.Context, *ListBlueprintsRequest) (*ListBlueprintsResponse, error)
}

// UnimplementedBlueprintServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBlueprintServiceServer struct {
}

func (*UnimplementedBlueprintServiceServer) GetBlueprint(ctx context.Context, req *GetBlueprintRequest) (*Blueprint, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlueprint not implemented")
}
func (*UnimplementedBlueprintServiceServer) ListBlueprints(ctx context.Context, req *ListBlueprintsRequest) (*ListBlueprintsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBlueprints not implemented")
}

func RegisterBlueprintServiceServer(s *grpc.Server, srv BlueprintServiceServer) {
	s.RegisterService(&_BlueprintService_serviceDesc, srv)
}

func _BlueprintService_GetBlueprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlueprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlueprintServiceServer).GetBlueprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/velocity.v1.BlueprintService/GetBlueprint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlueprintServiceServer).GetBlueprint(ctx, req.(*GetBlueprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlueprintService_ListBlueprints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBlueprintsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlueprintServiceServer).ListBlueprints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/velocity.v1.BlueprintService/ListBlueprints",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlueprintServiceServer).ListBlueprints(ctx, req.(*ListBlueprintsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlueprintService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "velocity.v1.BlueprintService",
	HandlerType: (*BlueprintServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlueprint",
			Handler:    _BlueprintService_GetBlueprint_Handler,
		},
		{
			MethodName: "ListBlueprints",
			Handler:    _BlueprintService_ListBlueprints_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blueprint.proto",
}
