// Code generated by protoc-gen-go. DO NOT EDIT.
// source: build.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Build_Status int32

const (
	Build_WAITING   Build_Status = 0
	Build_BUILDING  Build_Status = 1
	Build_SUCCEEDED Build_Status = 2
	Build_FAILED    Build_Status = 3
)

var Build_Status_name = map[int32]string{
	0: "WAITING",
	1: "BUILDING",
	2: "SUCCEEDED",
	3: "FAILED",
}

var Build_Status_value = map[string]int32{
	"WAITING":   0,
	"BUILDING":  1,
	"SUCCEEDED": 2,
	"FAILED":    3,
}

func (x Build_Status) String() string {
	return proto.EnumName(Build_Status_name, int32(x))
}

func (Build_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_14ce178a580e4ede, []int{0, 0}
}

type Stanza_Status int32

const (
	Stanza_WAITING   Stanza_Status = 0
	Stanza_BUILDING  Stanza_Status = 1
	Stanza_SUCCEEDED Stanza_Status = 2
	Stanza_FAILED    Stanza_Status = 3
)

var Stanza_Status_name = map[int32]string{
	0: "WAITING",
	1: "BUILDING",
	2: "SUCCEEDED",
	3: "FAILED",
}

var Stanza_Status_value = map[string]int32{
	"WAITING":   0,
	"BUILDING":  1,
	"SUCCEEDED": 2,
	"FAILED":    3,
}

func (x Stanza_Status) String() string {
	return proto.EnumName(Stanza_Status_name, int32(x))
}

func (Stanza_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_14ce178a580e4ede, []int{1, 0}
}

type Build struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId            string               `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	HeadId               string               `protobuf:"bytes,3,opt,name=head_id,json=headId,proto3" json:"head_id,omitempty"`
	CommitId             string               `protobuf:"bytes,4,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	Name                 string               `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Stanzas              []*Stanza            `protobuf:"bytes,6,rep,name=stanzas,proto3" json:"stanzas,omitempty"`
	Status               Build_Status         `protobuf:"varint,20,opt,name=status,proto3,enum=velocity.v1.Build_Status" json:"status,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,21,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,22,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Build) Reset()         { *m = Build{} }
func (m *Build) String() string { return proto.CompactTextString(m) }
func (*Build) ProtoMessage()    {}
func (*Build) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ce178a580e4ede, []int{0}
}

func (m *Build) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Build.Unmarshal(m, b)
}
func (m *Build) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Build.Marshal(b, m, deterministic)
}
func (m *Build) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Build.Merge(m, src)
}
func (m *Build) XXX_Size() int {
	return xxx_messageInfo_Build.Size(m)
}
func (m *Build) XXX_DiscardUnknown() {
	xxx_messageInfo_Build.DiscardUnknown(m)
}

var xxx_messageInfo_Build proto.InternalMessageInfo

func (m *Build) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Build) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *Build) GetHeadId() string {
	if m != nil {
		return m.HeadId
	}
	return ""
}

func (m *Build) GetCommitId() string {
	if m != nil {
		return m.CommitId
	}
	return ""
}

func (m *Build) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Build) GetStanzas() []*Stanza {
	if m != nil {
		return m.Stanzas
	}
	return nil
}

func (m *Build) GetStatus() Build_Status {
	if m != nil {
		return m.Status
	}
	return Build_WAITING
}

func (m *Build) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Build) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type Stanza struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BuildId              string               `protobuf:"bytes,2,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Tasks                map[string]*Task     `protobuf:"bytes,3,rep,name=tasks,proto3" json:"tasks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Status               Stanza_Status        `protobuf:"varint,20,opt,name=status,proto3,enum=velocity.v1.Stanza_Status" json:"status,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,21,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,22,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Stanza) Reset()         { *m = Stanza{} }
func (m *Stanza) String() string { return proto.CompactTextString(m) }
func (*Stanza) ProtoMessage()    {}
func (*Stanza) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ce178a580e4ede, []int{1}
}

func (m *Stanza) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stanza.Unmarshal(m, b)
}
func (m *Stanza) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stanza.Marshal(b, m, deterministic)
}
func (m *Stanza) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stanza.Merge(m, src)
}
func (m *Stanza) XXX_Size() int {
	return xxx_messageInfo_Stanza.Size(m)
}
func (m *Stanza) XXX_DiscardUnknown() {
	xxx_messageInfo_Stanza.DiscardUnknown(m)
}

var xxx_messageInfo_Stanza proto.InternalMessageInfo

func (m *Stanza) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Stanza) GetBuildId() string {
	if m != nil {
		return m.BuildId
	}
	return ""
}

func (m *Stanza) GetTasks() map[string]*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *Stanza) GetStatus() Stanza_Status {
	if m != nil {
		return m.Status
	}
	return Stanza_WAITING
}

func (m *Stanza) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Stanza) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type CreateBuildRequest struct {
	// The id of the project in the form of
	// `[PROJECT_ID]`.
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// The id of the head in the form of
	// `[HEAD_ID]`. Can be blank if building a commit with no head.
	HeadId string `protobuf:"bytes,2,opt,name=head_id,json=headId,proto3" json:"head_id,omitempty"`
	// The id of the blueprint/pipeline in the form of
	// `[BLUEPRINT/PIPELINE_ID]`.
	TargetId             string            `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Parameters           map[string]string `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateBuildRequest) Reset()         { *m = CreateBuildRequest{} }
func (m *CreateBuildRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBuildRequest) ProtoMessage()    {}
func (*CreateBuildRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ce178a580e4ede, []int{2}
}

func (m *CreateBuildRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBuildRequest.Unmarshal(m, b)
}
func (m *CreateBuildRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBuildRequest.Marshal(b, m, deterministic)
}
func (m *CreateBuildRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBuildRequest.Merge(m, src)
}
func (m *CreateBuildRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBuildRequest.Size(m)
}
func (m *CreateBuildRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBuildRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBuildRequest proto.InternalMessageInfo

func (m *CreateBuildRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *CreateBuildRequest) GetHeadId() string {
	if m != nil {
		return m.HeadId
	}
	return ""
}

func (m *CreateBuildRequest) GetTargetId() string {
	if m != nil {
		return m.TargetId
	}
	return ""
}

func (m *CreateBuildRequest) GetParameters() map[string]string {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type GetBuildRequest struct {
	// The id of the project in the form of
	// `[PROJECT_ID]`.
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// The id of the build in the form of
	// `[BUILD_ID]`.
	BuildId              string   `protobuf:"bytes,2,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBuildRequest) Reset()         { *m = GetBuildRequest{} }
func (m *GetBuildRequest) String() string { return proto.CompactTextString(m) }
func (*GetBuildRequest) ProtoMessage()    {}
func (*GetBuildRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ce178a580e4ede, []int{3}
}

func (m *GetBuildRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBuildRequest.Unmarshal(m, b)
}
func (m *GetBuildRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBuildRequest.Marshal(b, m, deterministic)
}
func (m *GetBuildRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBuildRequest.Merge(m, src)
}
func (m *GetBuildRequest) XXX_Size() int {
	return xxx_messageInfo_GetBuildRequest.Size(m)
}
func (m *GetBuildRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBuildRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBuildRequest proto.InternalMessageInfo

func (m *GetBuildRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *GetBuildRequest) GetBuildId() string {
	if m != nil {
		return m.BuildId
	}
	return ""
}

type TargetQuery struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TargetQuery) Reset()         { *m = TargetQuery{} }
func (m *TargetQuery) String() string { return proto.CompactTextString(m) }
func (*TargetQuery) ProtoMessage()    {}
func (*TargetQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ce178a580e4ede, []int{4}
}

func (m *TargetQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TargetQuery.Unmarshal(m, b)
}
func (m *TargetQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TargetQuery.Marshal(b, m, deterministic)
}
func (m *TargetQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TargetQuery.Merge(m, src)
}
func (m *TargetQuery) XXX_Size() int {
	return xxx_messageInfo_TargetQuery.Size(m)
}
func (m *TargetQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_TargetQuery.DiscardUnknown(m)
}

var xxx_messageInfo_TargetQuery proto.InternalMessageInfo

func (m *TargetQuery) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type ListBuildsRequest struct {
	RepoQuery            *RepoQuery   `protobuf:"bytes,1,opt,name=repo_query,json=repoQuery,proto3" json:"repo_query,omitempty"`
	TargetQuery          *TargetQuery `protobuf:"bytes,2,opt,name=target_query,json=targetQuery,proto3" json:"target_query,omitempty"`
	PageQuery            *PageQuery   `protobuf:"bytes,99,opt,name=page_query,json=pageQuery,proto3" json:"page_query,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListBuildsRequest) Reset()         { *m = ListBuildsRequest{} }
func (m *ListBuildsRequest) String() string { return proto.CompactTextString(m) }
func (*ListBuildsRequest) ProtoMessage()    {}
func (*ListBuildsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ce178a580e4ede, []int{5}
}

func (m *ListBuildsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBuildsRequest.Unmarshal(m, b)
}
func (m *ListBuildsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBuildsRequest.Marshal(b, m, deterministic)
}
func (m *ListBuildsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBuildsRequest.Merge(m, src)
}
func (m *ListBuildsRequest) XXX_Size() int {
	return xxx_messageInfo_ListBuildsRequest.Size(m)
}
func (m *ListBuildsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBuildsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBuildsRequest proto.InternalMessageInfo

func (m *ListBuildsRequest) GetRepoQuery() *RepoQuery {
	if m != nil {
		return m.RepoQuery
	}
	return nil
}

func (m *ListBuildsRequest) GetTargetQuery() *TargetQuery {
	if m != nil {
		return m.TargetQuery
	}
	return nil
}

func (m *ListBuildsRequest) GetPageQuery() *PageQuery {
	if m != nil {
		return m.PageQuery
	}
	return nil
}

type ListBuildsResponse struct {
	Builds               []*Build `protobuf:"bytes,1,rep,name=builds,proto3" json:"builds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBuildsResponse) Reset()         { *m = ListBuildsResponse{} }
func (m *ListBuildsResponse) String() string { return proto.CompactTextString(m) }
func (*ListBuildsResponse) ProtoMessage()    {}
func (*ListBuildsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ce178a580e4ede, []int{6}
}

func (m *ListBuildsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBuildsResponse.Unmarshal(m, b)
}
func (m *ListBuildsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBuildsResponse.Marshal(b, m, deterministic)
}
func (m *ListBuildsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBuildsResponse.Merge(m, src)
}
func (m *ListBuildsResponse) XXX_Size() int {
	return xxx_messageInfo_ListBuildsResponse.Size(m)
}
func (m *ListBuildsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBuildsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBuildsResponse proto.InternalMessageInfo

func (m *ListBuildsResponse) GetBuilds() []*Build {
	if m != nil {
		return m.Builds
	}
	return nil
}

func init() {
	proto.RegisterEnum("velocity.v1.Build_Status", Build_Status_name, Build_Status_value)
	proto.RegisterEnum("velocity.v1.Stanza_Status", Stanza_Status_name, Stanza_Status_value)
	proto.RegisterType((*Build)(nil), "velocity.v1.Build")
	proto.RegisterType((*Stanza)(nil), "velocity.v1.Stanza")
	proto.RegisterMapType((map[string]*Task)(nil), "velocity.v1.Stanza.TasksEntry")
	proto.RegisterType((*CreateBuildRequest)(nil), "velocity.v1.CreateBuildRequest")
	proto.RegisterMapType((map[string]string)(nil), "velocity.v1.CreateBuildRequest.ParametersEntry")
	proto.RegisterType((*GetBuildRequest)(nil), "velocity.v1.GetBuildRequest")
	proto.RegisterType((*TargetQuery)(nil), "velocity.v1.TargetQuery")
	proto.RegisterType((*ListBuildsRequest)(nil), "velocity.v1.ListBuildsRequest")
	proto.RegisterType((*ListBuildsResponse)(nil), "velocity.v1.ListBuildsResponse")
}

func init() { proto.RegisterFile("build.proto", fileDescriptor_14ce178a580e4ede) }

var fileDescriptor_14ce178a580e4ede = []byte{
	// 801 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0xcd, 0x8e, 0xdc, 0x44,
	0x10, 0xc6, 0xf6, 0xfc, 0xb9, 0xbc, 0x24, 0x93, 0x22, 0x04, 0xc7, 0x2c, 0x3b, 0x23, 0x8b, 0x9f,
	0xd1, 0x22, 0x6c, 0x8d, 0x21, 0x12, 0x04, 0x05, 0x31, 0xbb, 0x33, 0x44, 0x56, 0x56, 0x10, 0xbc,
	0x13, 0x21, 0x71, 0x59, 0xf5, 0x8e, 0x9b, 0xc1, 0x64, 0xc6, 0x76, 0xdc, 0xed, 0x91, 0x26, 0x28,
	0x17, 0x5e, 0x81, 0x0b, 0x47, 0x9e, 0x84, 0x97, 0xe0, 0xc6, 0x99, 0x97, 0xe0, 0x86, 0xdc, 0x6d,
	0x67, 0x7e, 0x93, 0x15, 0xe2, 0x92, 0x93, 0xdb, 0x55, 0xf5, 0xf5, 0x57, 0xf5, 0x55, 0x75, 0x81,
	0x71, 0x99, 0x47, 0xb3, 0xd0, 0x49, 0xb3, 0x84, 0x27, 0x68, 0x2c, 0xe8, 0x2c, 0x99, 0x44, 0x7c,
	0xe9, 0x2c, 0xfa, 0x96, 0x4e, 0xd2, 0x48, 0xda, 0xad, 0x76, 0x46, 0xd3, 0x84, 0x45, 0x3c, 0xc9,
	0x96, 0xa5, 0x05, 0x38, 0x61, 0x8f, 0xcb, 0xf3, 0xe1, 0x34, 0x49, 0xa6, 0x33, 0xea, 0x92, 0x34,
	0x72, 0x49, 0x1c, 0x27, 0x9c, 0xf0, 0x28, 0x89, 0x59, 0xe9, 0xed, 0x94, 0x5e, 0xf1, 0x77, 0x99,
	0xff, 0xe0, 0xf2, 0x68, 0x4e, 0x19, 0x27, 0xf3, 0x54, 0x06, 0xd8, 0xbf, 0x69, 0x50, 0x3f, 0x29,
	0x92, 0xc0, 0x6b, 0xa0, 0x46, 0xa1, 0xa9, 0x74, 0x95, 0x9e, 0x1e, 0xa8, 0x51, 0x88, 0xef, 0x00,
	0xa4, 0x59, 0xf2, 0x13, 0x9d, 0xf0, 0x8b, 0x28, 0x34, 0x55, 0x61, 0xd7, 0x4b, 0x8b, 0x1f, 0xe2,
	0x5b, 0xd0, 0xfc, 0x91, 0x92, 0xb0, 0xf0, 0x69, 0xc2, 0xd7, 0x28, 0x7e, 0xfd, 0x10, 0xdf, 0x06,
	0x7d, 0x92, 0xcc, 0xe7, 0x91, 0x80, 0xd5, 0x84, 0xab, 0x25, 0x0d, 0x7e, 0x88, 0x08, 0xb5, 0x98,
	0xcc, 0xa9, 0x59, 0x17, 0x76, 0x71, 0xc6, 0x8f, 0xa0, 0xc9, 0x38, 0x89, 0x9f, 0x12, 0x66, 0x36,
	0xba, 0x5a, 0xcf, 0xf0, 0xde, 0x70, 0xd6, 0x94, 0x70, 0xce, 0x85, 0x2f, 0xa8, 0x62, 0xb0, 0x0f,
	0x0d, 0xc6, 0x09, 0xcf, 0x99, 0x79, 0xb3, 0xab, 0xf4, 0xae, 0x79, 0xb7, 0x37, 0xa2, 0x45, 0x2d,
	0x05, 0x86, 0xe7, 0x2c, 0x28, 0x03, 0xf1, 0x33, 0x80, 0x49, 0x46, 0x09, 0xa7, 0xe1, 0x05, 0xe1,
	0xe6, 0x9b, 0x5d, 0xa5, 0x67, 0x78, 0x96, 0x23, 0xa5, 0x71, 0x2a, 0x69, 0x9c, 0x71, 0x25, 0x4d,
	0xa0, 0x97, 0xd1, 0x03, 0x5e, 0x40, 0xf3, 0x34, 0xac, 0xa0, 0xb7, 0xae, 0x86, 0x96, 0xd1, 0x03,
	0x6e, 0x7f, 0x01, 0x0d, 0x99, 0x07, 0x1a, 0xd0, 0xfc, 0x6e, 0xe0, 0x8f, 0xfd, 0xaf, 0xef, 0xb7,
	0x5f, 0xc3, 0x03, 0x68, 0x9d, 0x3c, 0xf2, 0xcf, 0x86, 0xc5, 0x9f, 0x82, 0xaf, 0x83, 0x7e, 0xfe,
	0xe8, 0xf4, 0x74, 0x34, 0x1a, 0x8e, 0x86, 0x6d, 0x15, 0x01, 0x1a, 0x5f, 0x0d, 0xfc, 0xb3, 0xd1,
	0xb0, 0xad, 0xd9, 0xbf, 0x6b, 0xe2, 0x82, 0xf8, 0x29, 0xd9, 0xe9, 0xcd, 0x6d, 0x68, 0x89, 0xc9,
	0x59, 0x75, 0xa6, 0x29, 0xfe, 0xfd, 0x10, 0x3f, 0x81, 0x7a, 0x31, 0x1d, 0xcc, 0xd4, 0x84, 0x96,
	0x47, 0x7b, 0xb4, 0x74, 0xc6, 0x45, 0xc0, 0x28, 0xe6, 0xd9, 0x32, 0x90, 0xc1, 0xe8, 0x6d, 0x89,
	0x6a, 0xed, 0x83, 0xbd, 0x0a, 0xaa, 0x5a, 0x0f, 0x00, 0x56, 0xe9, 0x63, 0x1b, 0xb4, 0xc7, 0x74,
	0x59, 0x2a, 0x53, 0x1c, 0xf1, 0x03, 0xa8, 0x2f, 0xc8, 0x2c, 0xa7, 0x42, 0x17, 0xc3, 0xbb, 0xb1,
	0x51, 0x48, 0x81, 0x0c, 0xa4, 0xff, 0xae, 0xfa, 0xa9, 0xf2, 0xbf, 0x5b, 0xf4, 0x8f, 0x02, 0x78,
	0x2a, 0xaa, 0x12, 0x73, 0x17, 0xd0, 0x27, 0x39, 0x65, 0x7c, 0xeb, 0xe9, 0x28, 0x2f, 0x79, 0x3a,
	0xea, 0xf6, 0xd3, 0xe1, 0x24, 0x9b, 0x52, 0xbe, 0x7a, 0x55, 0x2d, 0x69, 0xf0, 0x43, 0xfc, 0x06,
	0x20, 0x25, 0x19, 0x99, 0x53, 0x4e, 0x33, 0x66, 0xd6, 0x44, 0x77, 0xdd, 0x8d, 0xea, 0x76, 0x33,
	0x71, 0x1e, 0x3e, 0x47, 0xc8, 0x76, 0xaf, 0x5d, 0x61, 0xdd, 0x83, 0xeb, 0x5b, 0xee, 0x3d, 0x72,
	0xde, 0x5c, 0x97, 0x53, 0x5f, 0xd7, 0xee, 0x01, 0x5c, 0xbf, 0x4f, 0xf9, 0x7f, 0xa9, 0xfb, 0xc5,
	0x53, 0x6b, 0x77, 0xc0, 0x18, 0x8b, 0x42, 0xbf, 0xcd, 0xa9, 0xcc, 0x23, 0x0a, 0x99, 0xa9, 0x74,
	0xb5, 0x22, 0x8f, 0x28, 0x64, 0xf6, 0x1f, 0x0a, 0xdc, 0x38, 0x8b, 0x98, 0xe4, 0x63, 0x15, 0xe1,
	0x1d, 0x80, 0x62, 0x39, 0x5e, 0x3c, 0x29, 0x50, 0x82, 0xd0, 0xf0, 0x6e, 0x6d, 0x68, 0x12, 0xd0,
	0x34, 0x11, 0x77, 0x06, 0x7a, 0x56, 0x1d, 0xf1, 0x73, 0x38, 0x28, 0x75, 0x96, 0x40, 0x39, 0x2a,
	0xe6, 0xd6, 0xa8, 0x3c, 0x4f, 0x27, 0x30, 0xf8, 0x5a, 0x6e, 0x77, 0x8a, 0x3e, 0x4c, 0x69, 0x09,
	0x9d, 0xec, 0xe1, 0x7c, 0x48, 0xa6, 0xb4, 0xe4, 0x4c, 0xab, 0xa3, 0xfd, 0x25, 0xe0, 0x7a, 0xfe,
	0x2c, 0x4d, 0x62, 0x46, 0xf1, 0x18, 0x1a, 0x42, 0x02, 0x59, 0xab, 0xe1, 0xe1, 0xee, 0x32, 0x0b,
	0xca, 0x08, 0xef, 0x2f, 0x15, 0x0e, 0x84, 0xe5, 0x9c, 0x66, 0x8b, 0x68, 0x42, 0x31, 0x01, 0x63,
	0xad, 0xe5, 0xd8, 0xb9, 0x62, 0x18, 0xac, 0x3d, 0x97, 0xdb, 0x1f, 0xfe, 0xf2, 0xe7, 0xdf, 0xbf,
	0xaa, 0xef, 0xd9, 0x87, 0xee, 0xa2, 0xef, 0xfe, 0x5c, 0xec, 0xe3, 0x7b, 0x65, 0xc3, 0x98, 0x7b,
	0xfc, 0xcc, 0x95, 0xd4, 0x77, 0xeb, 0xe2, 0x8b, 0x21, 0xb4, 0xaa, 0x96, 0xe3, 0xe1, 0xc6, 0x65,
	0x5b, 0x93, 0xb0, 0x97, 0xea, 0x7d, 0x41, 0xd5, 0xc5, 0xa3, 0x7d, 0x54, 0x25, 0x93, 0x7b, 0xfc,
	0x0c, 0x19, 0xc0, 0x4a, 0x29, 0xdc, 0x5c, 0x60, 0x3b, 0x23, 0x60, 0x75, 0x5e, 0xe8, 0x97, 0x12,
	0xdb, 0xef, 0x0a, 0xda, 0x23, 0x7c, 0x69, 0x85, 0x27, 0xb5, 0xef, 0xd5, 0x45, 0xff, 0xb2, 0x21,
	0x76, 0xcf, 0xc7, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x3f, 0xb6, 0xf2, 0x98, 0x07, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BuildServiceClient is the client API for BuildService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BuildServiceClient interface {
	CreateBuild(ctx context.Context, in *CreateBuildRequest, opts ...grpc.CallOption) (*Build, error)
	GetBuild(ctx context.Context, in *GetBuildRequest, opts ...grpc.CallOption) (*Build, error)
	ListBuilds(ctx context.Context, in *ListBuildsRequest, opts ...grpc.CallOption) (*ListBuildsResponse, error)
}

type buildServiceClient struct {
	cc *grpc.ClientConn
}

func NewBuildServiceClient(cc *grpc.ClientConn) BuildServiceClient {
	return &buildServiceClient{cc}
}

func (c *buildServiceClient) CreateBuild(ctx context.Context, in *CreateBuildRequest, opts ...grpc.CallOption) (*Build, error) {
	out := new(Build)
	err := c.cc.Invoke(ctx, "/velocity.v1.BuildService/CreateBuild", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildServiceClient) GetBuild(ctx context.Context, in *GetBuildRequest, opts ...grpc.CallOption) (*Build, error) {
	out := new(Build)
	err := c.cc.Invoke(ctx, "/velocity.v1.BuildService/GetBuild", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildServiceClient) ListBuilds(ctx context.Context, in *ListBuildsRequest, opts ...grpc.CallOption) (*ListBuildsResponse, error) {
	out := new(ListBuildsResponse)
	err := c.cc.Invoke(ctx, "/velocity.v1.BuildService/ListBuilds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuildServiceServer is the server API for BuildService service.
type BuildServiceServer interface {
	CreateBuild(context.Context, *CreateBuildRequest) (*Build, error)
	GetBuild(context.Context, *GetBuildRequest) (*Build, error)
	ListBuilds(context.Context, *ListBuildsRequest) (*ListBuildsResponse, error)
}

// UnimplementedBuildServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBuildServiceServer struct {
}

func (*UnimplementedBuildServiceServer) CreateBuild(ctx context.Context, req *CreateBuildRequest) (*Build, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBuild not implemented")
}
func (*UnimplementedBuildServiceServer) GetBuild(ctx context.Context, req *GetBuildRequest) (*Build, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBuild not implemented")
}
func (*UnimplementedBuildServiceServer) ListBuilds(ctx context.Context, req *ListBuildsRequest) (*ListBuildsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBuilds not implemented")
}

func RegisterBuildServiceServer(s *grpc.Server, srv BuildServiceServer) {
	s.RegisterService(&_BuildService_serviceDesc, srv)
}

func _BuildService_CreateBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildServiceServer).CreateBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/velocity.v1.BuildService/CreateBuild",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildServiceServer).CreateBuild(ctx, req.(*CreateBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildService_GetBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildServiceServer).GetBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/velocity.v1.BuildService/GetBuild",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildServiceServer).GetBuild(ctx, req.(*GetBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildService_ListBuilds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBuildsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildServiceServer).ListBuilds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/velocity.v1.BuildService/ListBuilds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildServiceServer).ListBuilds(ctx, req.(*ListBuildsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BuildService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "velocity.v1.BuildService",
	HandlerType: (*BuildServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBuild",
			Handler:    _BuildService_CreateBuild_Handler,
		},
		{
			MethodName: "GetBuild",
			Handler:    _BuildService_GetBuild_Handler,
		},
		{
			MethodName: "ListBuilds",
			Handler:    _BuildService_ListBuilds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "build.proto",
}
