// Code generated by protoc-gen-go. DO NOT EDIT.
// source: repository.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RepoQuery_Type int32

const (
	RepoQuery_HEAD   RepoQuery_Type = 0
	RepoQuery_COMMIT RepoQuery_Type = 1
)

var RepoQuery_Type_name = map[int32]string{
	0: "HEAD",
	1: "COMMIT",
}

var RepoQuery_Type_value = map[string]int32{
	"HEAD":   0,
	"COMMIT": 1,
}

func (x RepoQuery_Type) String() string {
	return proto.EnumName(RepoQuery_Type_name, int32(x))
}

func (RepoQuery_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{6, 0}
}

type Head struct {
	// HEAD_ID=head_name
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId            string   `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Head) Reset()         { *m = Head{} }
func (m *Head) String() string { return proto.CompactTextString(m) }
func (*Head) ProtoMessage()    {}
func (*Head) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{0}
}

func (m *Head) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Head.Unmarshal(m, b)
}
func (m *Head) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Head.Marshal(b, m, deterministic)
}
func (m *Head) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Head.Merge(m, src)
}
func (m *Head) XXX_Size() int {
	return xxx_messageInfo_Head.Size(m)
}
func (m *Head) XXX_DiscardUnknown() {
	xxx_messageInfo_Head.DiscardUnknown(m)
}

var xxx_messageInfo_Head proto.InternalMessageInfo

func (m *Head) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Head) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type Commit struct {
	// COMMIT_ID=commit_sha
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId            string   `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Commit) Reset()         { *m = Commit{} }
func (m *Commit) String() string { return proto.CompactTextString(m) }
func (*Commit) ProtoMessage()    {}
func (*Commit) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{1}
}

func (m *Commit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commit.Unmarshal(m, b)
}
func (m *Commit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commit.Marshal(b, m, deterministic)
}
func (m *Commit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commit.Merge(m, src)
}
func (m *Commit) XXX_Size() int {
	return xxx_messageInfo_Commit.Size(m)
}
func (m *Commit) XXX_DiscardUnknown() {
	xxx_messageInfo_Commit.DiscardUnknown(m)
}

var xxx_messageInfo_Commit proto.InternalMessageInfo

func (m *Commit) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Commit) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type Repository struct {
	Address              string     `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	SshConfig            *SSHConfig `protobuf:"bytes,2,opt,name=ssh_config,json=sshConfig,proto3" json:"ssh_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Repository) Reset()         { *m = Repository{} }
func (m *Repository) String() string { return proto.CompactTextString(m) }
func (*Repository) ProtoMessage()    {}
func (*Repository) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{2}
}

func (m *Repository) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Repository.Unmarshal(m, b)
}
func (m *Repository) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Repository.Marshal(b, m, deterministic)
}
func (m *Repository) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Repository.Merge(m, src)
}
func (m *Repository) XXX_Size() int {
	return xxx_messageInfo_Repository.Size(m)
}
func (m *Repository) XXX_DiscardUnknown() {
	xxx_messageInfo_Repository.DiscardUnknown(m)
}

var xxx_messageInfo_Repository proto.InternalMessageInfo

func (m *Repository) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Repository) GetSshConfig() *SSHConfig {
	if m != nil {
		return m.SshConfig
	}
	return nil
}

type SSHConfig struct {
	PrivateKey           string   `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	HostKey              string   `protobuf:"bytes,2,opt,name=host_key,json=hostKey,proto3" json:"host_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SSHConfig) Reset()         { *m = SSHConfig{} }
func (m *SSHConfig) String() string { return proto.CompactTextString(m) }
func (*SSHConfig) ProtoMessage()    {}
func (*SSHConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{3}
}

func (m *SSHConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SSHConfig.Unmarshal(m, b)
}
func (m *SSHConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SSHConfig.Marshal(b, m, deterministic)
}
func (m *SSHConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SSHConfig.Merge(m, src)
}
func (m *SSHConfig) XXX_Size() int {
	return xxx_messageInfo_SSHConfig.Size(m)
}
func (m *SSHConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SSHConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SSHConfig proto.InternalMessageInfo

func (m *SSHConfig) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func (m *SSHConfig) GetHostKey() string {
	if m != nil {
		return m.HostKey
	}
	return ""
}

type GetHeadRequest struct {
	// The id of the project in the form of
	// `[PROJECT_ID]`.
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// The id of the project in the form of
	// `[HEAD_ID]`.
	HeadId               string   `protobuf:"bytes,2,opt,name=head_id,json=headId,proto3" json:"head_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHeadRequest) Reset()         { *m = GetHeadRequest{} }
func (m *GetHeadRequest) String() string { return proto.CompactTextString(m) }
func (*GetHeadRequest) ProtoMessage()    {}
func (*GetHeadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{4}
}

func (m *GetHeadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHeadRequest.Unmarshal(m, b)
}
func (m *GetHeadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHeadRequest.Marshal(b, m, deterministic)
}
func (m *GetHeadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHeadRequest.Merge(m, src)
}
func (m *GetHeadRequest) XXX_Size() int {
	return xxx_messageInfo_GetHeadRequest.Size(m)
}
func (m *GetHeadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHeadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHeadRequest proto.InternalMessageInfo

func (m *GetHeadRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *GetHeadRequest) GetHeadId() string {
	if m != nil {
		return m.HeadId
	}
	return ""
}

type GetCommitRequest struct {
	// The id of the project in the form of
	// `[PROJECT_ID]`.
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// The id of the commit in the form of
	// `[COMMIT_ID]`.
	CommitId             string   `protobuf:"bytes,2,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCommitRequest) Reset()         { *m = GetCommitRequest{} }
func (m *GetCommitRequest) String() string { return proto.CompactTextString(m) }
func (*GetCommitRequest) ProtoMessage()    {}
func (*GetCommitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{5}
}

func (m *GetCommitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommitRequest.Unmarshal(m, b)
}
func (m *GetCommitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommitRequest.Marshal(b, m, deterministic)
}
func (m *GetCommitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommitRequest.Merge(m, src)
}
func (m *GetCommitRequest) XXX_Size() int {
	return xxx_messageInfo_GetCommitRequest.Size(m)
}
func (m *GetCommitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommitRequest proto.InternalMessageInfo

func (m *GetCommitRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *GetCommitRequest) GetCommitId() string {
	if m != nil {
		return m.CommitId
	}
	return ""
}

type RepoQuery struct {
	Type                 RepoQuery_Type `protobuf:"varint,1,opt,name=type,proto3,enum=velocity.v1.RepoQuery_Type" json:"type,omitempty"`
	Ids                  []string       `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RepoQuery) Reset()         { *m = RepoQuery{} }
func (m *RepoQuery) String() string { return proto.CompactTextString(m) }
func (*RepoQuery) ProtoMessage()    {}
func (*RepoQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{6}
}

func (m *RepoQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepoQuery.Unmarshal(m, b)
}
func (m *RepoQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepoQuery.Marshal(b, m, deterministic)
}
func (m *RepoQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepoQuery.Merge(m, src)
}
func (m *RepoQuery) XXX_Size() int {
	return xxx_messageInfo_RepoQuery.Size(m)
}
func (m *RepoQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_RepoQuery.DiscardUnknown(m)
}

var xxx_messageInfo_RepoQuery proto.InternalMessageInfo

func (m *RepoQuery) GetType() RepoQuery_Type {
	if m != nil {
		return m.Type
	}
	return RepoQuery_HEAD
}

func (m *RepoQuery) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type ListHeadsRequest struct {
	// The id of the project in the form of
	// `[PROJECT_ID]`.
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// The ids of the commits in the form of
	// `[COMMIT_ID]`.
	CommitIds            []string   `protobuf:"bytes,2,rep,name=commit_ids,json=commitIds,proto3" json:"commit_ids,omitempty"`
	PageQuery            *PageQuery `protobuf:"bytes,99,opt,name=page_query,json=pageQuery,proto3" json:"page_query,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListHeadsRequest) Reset()         { *m = ListHeadsRequest{} }
func (m *ListHeadsRequest) String() string { return proto.CompactTextString(m) }
func (*ListHeadsRequest) ProtoMessage()    {}
func (*ListHeadsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{7}
}

func (m *ListHeadsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHeadsRequest.Unmarshal(m, b)
}
func (m *ListHeadsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHeadsRequest.Marshal(b, m, deterministic)
}
func (m *ListHeadsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHeadsRequest.Merge(m, src)
}
func (m *ListHeadsRequest) XXX_Size() int {
	return xxx_messageInfo_ListHeadsRequest.Size(m)
}
func (m *ListHeadsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHeadsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListHeadsRequest proto.InternalMessageInfo

func (m *ListHeadsRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *ListHeadsRequest) GetCommitIds() []string {
	if m != nil {
		return m.CommitIds
	}
	return nil
}

func (m *ListHeadsRequest) GetPageQuery() *PageQuery {
	if m != nil {
		return m.PageQuery
	}
	return nil
}

type ListHeadsResponse struct {
	Heads                []*Head  `protobuf:"bytes,1,rep,name=heads,proto3" json:"heads,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListHeadsResponse) Reset()         { *m = ListHeadsResponse{} }
func (m *ListHeadsResponse) String() string { return proto.CompactTextString(m) }
func (*ListHeadsResponse) ProtoMessage()    {}
func (*ListHeadsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{8}
}

func (m *ListHeadsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHeadsResponse.Unmarshal(m, b)
}
func (m *ListHeadsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHeadsResponse.Marshal(b, m, deterministic)
}
func (m *ListHeadsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHeadsResponse.Merge(m, src)
}
func (m *ListHeadsResponse) XXX_Size() int {
	return xxx_messageInfo_ListHeadsResponse.Size(m)
}
func (m *ListHeadsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHeadsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListHeadsResponse proto.InternalMessageInfo

func (m *ListHeadsResponse) GetHeads() []*Head {
	if m != nil {
		return m.Heads
	}
	return nil
}

type ListCommitsRequest struct {
	// The id of the project in the form of
	// `[PROJECT_ID]`.
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// The ids of the heads in the form of
	// `[HEAD_ID]`.
	HeadIds              []string   `protobuf:"bytes,2,rep,name=head_ids,json=headIds,proto3" json:"head_ids,omitempty"`
	PageQuery            *PageQuery `protobuf:"bytes,99,opt,name=page_query,json=pageQuery,proto3" json:"page_query,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListCommitsRequest) Reset()         { *m = ListCommitsRequest{} }
func (m *ListCommitsRequest) String() string { return proto.CompactTextString(m) }
func (*ListCommitsRequest) ProtoMessage()    {}
func (*ListCommitsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{9}
}

func (m *ListCommitsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCommitsRequest.Unmarshal(m, b)
}
func (m *ListCommitsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCommitsRequest.Marshal(b, m, deterministic)
}
func (m *ListCommitsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCommitsRequest.Merge(m, src)
}
func (m *ListCommitsRequest) XXX_Size() int {
	return xxx_messageInfo_ListCommitsRequest.Size(m)
}
func (m *ListCommitsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCommitsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCommitsRequest proto.InternalMessageInfo

func (m *ListCommitsRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *ListCommitsRequest) GetHeadIds() []string {
	if m != nil {
		return m.HeadIds
	}
	return nil
}

func (m *ListCommitsRequest) GetPageQuery() *PageQuery {
	if m != nil {
		return m.PageQuery
	}
	return nil
}

type ListCommitsResponse struct {
	Commits              []*Commit `protobuf:"bytes,1,rep,name=commits,proto3" json:"commits,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListCommitsResponse) Reset()         { *m = ListCommitsResponse{} }
func (m *ListCommitsResponse) String() string { return proto.CompactTextString(m) }
func (*ListCommitsResponse) ProtoMessage()    {}
func (*ListCommitsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{10}
}

func (m *ListCommitsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCommitsResponse.Unmarshal(m, b)
}
func (m *ListCommitsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCommitsResponse.Marshal(b, m, deterministic)
}
func (m *ListCommitsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCommitsResponse.Merge(m, src)
}
func (m *ListCommitsResponse) XXX_Size() int {
	return xxx_messageInfo_ListCommitsResponse.Size(m)
}
func (m *ListCommitsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCommitsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCommitsResponse proto.InternalMessageInfo

func (m *ListCommitsResponse) GetCommits() []*Commit {
	if m != nil {
		return m.Commits
	}
	return nil
}

func init() {
	proto.RegisterEnum("velocity.v1.RepoQuery_Type", RepoQuery_Type_name, RepoQuery_Type_value)
	proto.RegisterType((*Head)(nil), "velocity.v1.Head")
	proto.RegisterType((*Commit)(nil), "velocity.v1.Commit")
	proto.RegisterType((*Repository)(nil), "velocity.v1.Repository")
	proto.RegisterType((*SSHConfig)(nil), "velocity.v1.SSHConfig")
	proto.RegisterType((*GetHeadRequest)(nil), "velocity.v1.GetHeadRequest")
	proto.RegisterType((*GetCommitRequest)(nil), "velocity.v1.GetCommitRequest")
	proto.RegisterType((*RepoQuery)(nil), "velocity.v1.RepoQuery")
	proto.RegisterType((*ListHeadsRequest)(nil), "velocity.v1.ListHeadsRequest")
	proto.RegisterType((*ListHeadsResponse)(nil), "velocity.v1.ListHeadsResponse")
	proto.RegisterType((*ListCommitsRequest)(nil), "velocity.v1.ListCommitsRequest")
	proto.RegisterType((*ListCommitsResponse)(nil), "velocity.v1.ListCommitsResponse")
}

func init() { proto.RegisterFile("repository.proto", fileDescriptor_10d86afa5a89ec9d) }

var fileDescriptor_10d86afa5a89ec9d = []byte{
	// 636 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xdd, 0x4e, 0x13, 0x41,
	0x14, 0xb6, 0x3f, 0xb6, 0xcc, 0x69, 0x42, 0xca, 0x90, 0x68, 0x2d, 0xd4, 0xe2, 0x18, 0x03, 0x21,
	0xb1, 0x1b, 0x6a, 0x88, 0x37, 0x7a, 0xa1, 0x60, 0x68, 0x83, 0xf8, 0xb3, 0x70, 0x65, 0x62, 0xea,
	0xda, 0x3d, 0xb6, 0xa3, 0xd0, 0x59, 0x76, 0x86, 0x35, 0x1b, 0xc3, 0x8d, 0x89, 0xf1, 0x01, 0x7c,
	0x2a, 0xaf, 0x7d, 0x05, 0x1f, 0xc4, 0xcc, 0xcc, 0xee, 0xc2, 0x96, 0x62, 0xd0, 0xbb, 0x99, 0x73,
	0x66, 0xcf, 0xf7, 0x73, 0xbe, 0x16, 0xea, 0x21, 0x06, 0x42, 0x72, 0x25, 0xc2, 0xb8, 0x13, 0x84,
	0x42, 0x09, 0x5a, 0x8b, 0xf0, 0x50, 0x0c, 0xb9, 0x8a, 0x3b, 0xd1, 0x46, 0x93, 0x78, 0x01, 0xb7,
	0xf5, 0xe6, 0xf2, 0x48, 0x88, 0xd1, 0x21, 0x3a, 0x5e, 0xc0, 0x1d, 0x6f, 0x32, 0x11, 0xca, 0x53,
	0x5c, 0x4c, 0xa4, 0xed, 0xb2, 0x4d, 0x28, 0xf7, 0xd0, 0xf3, 0xe9, 0x3c, 0x14, 0xb9, 0xdf, 0x28,
	0xac, 0x14, 0xd6, 0x88, 0x5b, 0xe4, 0x3e, 0x6d, 0x01, 0x04, 0xa1, 0xf8, 0x88, 0x43, 0x35, 0xe0,
	0x7e, 0xa3, 0x68, 0xea, 0x24, 0xa9, 0xf4, 0x7d, 0xf6, 0x10, 0x2a, 0x5b, 0xe2, 0xe8, 0x88, 0xab,
	0x7f, 0xfd, 0xf0, 0x2d, 0x80, 0x9b, 0x31, 0xa7, 0x0d, 0xa8, 0x7a, 0xbe, 0x1f, 0xa2, 0x94, 0xc9,
	0x84, 0xf4, 0x4a, 0x37, 0x01, 0xa4, 0x1c, 0x0f, 0x86, 0x62, 0xf2, 0x81, 0x8f, 0xcc, 0x98, 0x5a,
	0xf7, 0x46, 0xe7, 0x9c, 0xc4, 0xce, 0xfe, 0x7e, 0x6f, 0xcb, 0x74, 0x5d, 0x22, 0xe5, 0xd8, 0x1e,
	0xd9, 0x0e, 0x90, 0xac, 0x4e, 0xdb, 0x50, 0x0b, 0x42, 0x1e, 0x79, 0x0a, 0x07, 0x9f, 0x30, 0x4e,
	0x10, 0x20, 0x29, 0xed, 0x62, 0x4c, 0x6f, 0xc1, 0xdc, 0x58, 0x48, 0x65, 0xba, 0x96, 0x69, 0x55,
	0xdf, 0x77, 0x31, 0x66, 0x3d, 0x98, 0xdf, 0x41, 0xa5, 0xad, 0x71, 0xf1, 0xf8, 0x04, 0xa5, 0x9a,
	0x12, 0x56, 0x98, 0x12, 0x46, 0x6f, 0x42, 0x75, 0x8c, 0x9e, 0x7f, 0x26, 0xba, 0xa2, 0xaf, 0x7d,
	0x9f, 0xbd, 0x80, 0xfa, 0x0e, 0x2a, 0xeb, 0xd6, 0x15, 0x67, 0x2d, 0x01, 0x19, 0x9a, 0xf7, 0x67,
	0xd3, 0xe6, 0x6c, 0xa1, 0xef, 0xb3, 0x43, 0x20, 0xda, 0xc1, 0xd7, 0x27, 0x18, 0xc6, 0xd4, 0x81,
	0xb2, 0x8a, 0x03, 0x34, 0x23, 0xe6, 0xbb, 0x4b, 0x39, 0x83, 0xb2, 0x57, 0x9d, 0x83, 0x38, 0x40,
	0xd7, 0x3c, 0xa4, 0x75, 0x28, 0x71, 0x5f, 0x36, 0x8a, 0x2b, 0xa5, 0x35, 0xe2, 0xea, 0x23, 0x5b,
	0x86, 0xb2, 0xee, 0xd3, 0x39, 0x28, 0xf7, 0x9e, 0x3d, 0xd9, 0xae, 0x5f, 0xa3, 0x00, 0x95, 0xad,
	0x97, 0x7b, 0x7b, 0xfd, 0x83, 0x7a, 0x81, 0x7d, 0x2f, 0x40, 0xfd, 0x39, 0x97, 0xc6, 0x09, 0x79,
	0x45, 0xfa, 0x2d, 0x80, 0x8c, 0x7e, 0x0a, 0x45, 0x52, 0xfe, 0x66, 0xb5, 0x81, 0x37, 0xc2, 0xc1,
	0xb1, 0xe6, 0xd6, 0x18, 0xce, 0x58, 0xed, 0x2b, 0x6f, 0x84, 0x86, 0xb9, 0x4b, 0x82, 0xf4, 0xc8,
	0x1e, 0xc1, 0xc2, 0x39, 0x22, 0x32, 0x10, 0x13, 0x89, 0x74, 0x15, 0xae, 0x6b, 0x9b, 0x75, 0x7c,
	0x4a, 0x6b, 0xb5, 0xee, 0x42, 0x6e, 0x8c, 0xd9, 0x9e, 0xed, 0xb3, 0x6f, 0x05, 0xa0, 0xfa, 0x73,
	0xbb, 0x87, 0xab, 0x2a, 0xd1, 0x01, 0xb1, 0x4b, 0x4d, 0x75, 0x54, 0xed, 0x56, 0xff, 0x5b, 0xc5,
	0x36, 0x2c, 0xe6, 0x68, 0x24, 0x3a, 0xee, 0x43, 0xd5, 0x1a, 0x94, 0x2a, 0x59, 0xcc, 0x8d, 0x4a,
	0xd2, 0x93, 0xbe, 0xe9, 0xfe, 0x2c, 0xc1, 0xc2, 0xd9, 0xcf, 0x68, 0x1f, 0xc3, 0x88, 0x0f, 0x91,
	0xbe, 0x83, 0x6a, 0x92, 0x59, 0x9a, 0x4f, 0x42, 0x3e, 0xc9, 0xcd, 0x8b, 0x2e, 0xb1, 0x7b, 0x5f,
	0x7f, 0xfd, 0xfe, 0x51, 0x6c, 0xd3, 0x96, 0x13, 0x6d, 0x38, 0x5f, 0x26, 0xde, 0x11, 0x3e, 0x4e,
	0x5c, 0x90, 0xce, 0xba, 0x63, 0x2c, 0x74, 0xd6, 0x4f, 0xe9, 0x18, 0x48, 0x96, 0x65, 0xda, 0x9a,
	0xc6, 0xc8, 0x65, 0xbc, 0x39, 0x4b, 0x01, 0x5b, 0x35, 0x38, 0x77, 0x68, 0x7b, 0x26, 0x4e, 0x22,
	0x4f, 0x23, 0x09, 0x20, 0xd9, 0xb6, 0xa7, 0x90, 0xa6, 0xe3, 0xd8, 0xbc, 0x7d, 0x59, 0xdb, 0x9a,
	0xcb, 0xee, 0x1a, 0xd0, 0x16, 0x5d, 0x9a, 0x05, 0x7a, 0x6a, 0xd5, 0xd1, 0xcf, 0x50, 0x3b, 0xb7,
	0x18, 0xda, 0xbe, 0x30, 0x33, 0x9f, 0x9c, 0xe6, 0xca, 0xe5, 0x0f, 0x12, 0xd8, 0xbf, 0x7a, 0x7a,
	0x9a, 0x8a, 0x7d, 0x5a, 0x7e, 0x53, 0x8c, 0x36, 0xde, 0x57, 0xcc, 0xdf, 0xf1, 0x83, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xd6, 0x71, 0x44, 0xcf, 0xd8, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RepositoryServiceClient is the client API for RepositoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RepositoryServiceClient interface {
	GetHead(ctx context.Context, in *GetHeadRequest, opts ...grpc.CallOption) (*Head, error)
	GetCommit(ctx context.Context, in *GetCommitRequest, opts ...grpc.CallOption) (*Commit, error)
	ListHeads(ctx context.Context, in *ListHeadsRequest, opts ...grpc.CallOption) (*ListHeadsResponse, error)
	ListCommits(ctx context.Context, in *ListCommitsRequest, opts ...grpc.CallOption) (*ListCommitsResponse, error)
}

type repositoryServiceClient struct {
	cc *grpc.ClientConn
}

func NewRepositoryServiceClient(cc *grpc.ClientConn) RepositoryServiceClient {
	return &repositoryServiceClient{cc}
}

func (c *repositoryServiceClient) GetHead(ctx context.Context, in *GetHeadRequest, opts ...grpc.CallOption) (*Head, error) {
	out := new(Head)
	err := c.cc.Invoke(ctx, "/velocity.v1.RepositoryService/GetHead", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryServiceClient) GetCommit(ctx context.Context, in *GetCommitRequest, opts ...grpc.CallOption) (*Commit, error) {
	out := new(Commit)
	err := c.cc.Invoke(ctx, "/velocity.v1.RepositoryService/GetCommit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryServiceClient) ListHeads(ctx context.Context, in *ListHeadsRequest, opts ...grpc.CallOption) (*ListHeadsResponse, error) {
	out := new(ListHeadsResponse)
	err := c.cc.Invoke(ctx, "/velocity.v1.RepositoryService/ListHeads", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryServiceClient) ListCommits(ctx context.Context, in *ListCommitsRequest, opts ...grpc.CallOption) (*ListCommitsResponse, error) {
	out := new(ListCommitsResponse)
	err := c.cc.Invoke(ctx, "/velocity.v1.RepositoryService/ListCommits", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RepositoryServiceServer is the server API for RepositoryService service.
type RepositoryServiceServer interface {
	GetHead(context.Context, *GetHeadRequest) (*Head, error)
	GetCommit(context.Context, *GetCommitRequest) (*Commit, error)
	ListHeads(context.Context, *ListHeadsRequest) (*ListHeadsResponse, error)
	ListCommits(context.Context, *ListCommitsRequest) (*ListCommitsResponse, error)
}

// UnimplementedRepositoryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRepositoryServiceServer struct {
}

func (*UnimplementedRepositoryServiceServer) GetHead(ctx context.Context, req *GetHeadRequest) (*Head, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHead not implemented")
}
func (*UnimplementedRepositoryServiceServer) GetCommit(ctx context.Context, req *GetCommitRequest) (*Commit, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommit not implemented")
}
func (*UnimplementedRepositoryServiceServer) ListHeads(ctx context.Context, req *ListHeadsRequest) (*ListHeadsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHeads not implemented")
}
func (*UnimplementedRepositoryServiceServer) ListCommits(ctx context.Context, req *ListCommitsRequest) (*ListCommitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCommits not implemented")
}

func RegisterRepositoryServiceServer(s *grpc.Server, srv RepositoryServiceServer) {
	s.RegisterService(&_RepositoryService_serviceDesc, srv)
}

func _RepositoryService_GetHead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHeadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServiceServer).GetHead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/velocity.v1.RepositoryService/GetHead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServiceServer).GetHead(ctx, req.(*GetHeadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepositoryService_GetCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServiceServer).GetCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/velocity.v1.RepositoryService/GetCommit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServiceServer).GetCommit(ctx, req.(*GetCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepositoryService_ListHeads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHeadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServiceServer).ListHeads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/velocity.v1.RepositoryService/ListHeads",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServiceServer).ListHeads(ctx, req.(*ListHeadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepositoryService_ListCommits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServiceServer).ListCommits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/velocity.v1.RepositoryService/ListCommits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServiceServer).ListCommits(ctx, req.(*ListCommitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RepositoryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "velocity.v1.RepositoryService",
	HandlerType: (*RepositoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHead",
			Handler:    _RepositoryService_GetHead_Handler,
		},
		{
			MethodName: "GetCommit",
			Handler:    _RepositoryService_GetCommit_Handler,
		},
		{
			MethodName: "ListHeads",
			Handler:    _RepositoryService_ListHeads_Handler,
		},
		{
			MethodName: "ListCommits",
			Handler:    _RepositoryService_ListCommits_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "repository.proto",
}
