// Code generated by protoc-gen-go. DO NOT EDIT.
// source: step.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Step struct {
	Id          string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description string               `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Streams     []*Stream            `protobuf:"bytes,3,rep,name=streams,proto3" json:"streams,omitempty"`
	Status      string               `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt   *timestamp.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	UpdatedAt   *timestamp.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Types that are valid to be assigned to Impl:
	//	*Step_Setup
	//	*Step_DockerRun
	//	*Step_DockerBuild
	//	*Step_DockerCompose
	//	*Step_DockerPush
	Impl                 isStep_Impl `protobuf_oneof:"impl"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Step) Reset()         { *m = Step{} }
func (m *Step) String() string { return proto.CompactTextString(m) }
func (*Step) ProtoMessage()    {}
func (*Step) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3716d53a7e1b752, []int{0}
}

func (m *Step) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Step.Unmarshal(m, b)
}
func (m *Step) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Step.Marshal(b, m, deterministic)
}
func (m *Step) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Step.Merge(m, src)
}
func (m *Step) XXX_Size() int {
	return xxx_messageInfo_Step.Size(m)
}
func (m *Step) XXX_DiscardUnknown() {
	xxx_messageInfo_Step.DiscardUnknown(m)
}

var xxx_messageInfo_Step proto.InternalMessageInfo

func (m *Step) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Step) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Step) GetStreams() []*Stream {
	if m != nil {
		return m.Streams
	}
	return nil
}

func (m *Step) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Step) GetStartedAt() *timestamp.Timestamp {
	if m != nil {
		return m.StartedAt
	}
	return nil
}

func (m *Step) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type isStep_Impl interface {
	isStep_Impl()
}

type Step_Setup struct {
	Setup *Setup `protobuf:"bytes,100,opt,name=setup,proto3,oneof"`
}

type Step_DockerRun struct {
	DockerRun *DockerRun `protobuf:"bytes,101,opt,name=docker_run,json=dockerRun,proto3,oneof"`
}

type Step_DockerBuild struct {
	DockerBuild *DockerBuild `protobuf:"bytes,102,opt,name=docker_build,json=dockerBuild,proto3,oneof"`
}

type Step_DockerCompose struct {
	DockerCompose *DockerCompose `protobuf:"bytes,103,opt,name=docker_compose,json=dockerCompose,proto3,oneof"`
}

type Step_DockerPush struct {
	DockerPush *DockerPush `protobuf:"bytes,104,opt,name=docker_push,json=dockerPush,proto3,oneof"`
}

func (*Step_Setup) isStep_Impl() {}

func (*Step_DockerRun) isStep_Impl() {}

func (*Step_DockerBuild) isStep_Impl() {}

func (*Step_DockerCompose) isStep_Impl() {}

func (*Step_DockerPush) isStep_Impl() {}

func (m *Step) GetImpl() isStep_Impl {
	if m != nil {
		return m.Impl
	}
	return nil
}

func (m *Step) GetSetup() *Setup {
	if x, ok := m.GetImpl().(*Step_Setup); ok {
		return x.Setup
	}
	return nil
}

func (m *Step) GetDockerRun() *DockerRun {
	if x, ok := m.GetImpl().(*Step_DockerRun); ok {
		return x.DockerRun
	}
	return nil
}

func (m *Step) GetDockerBuild() *DockerBuild {
	if x, ok := m.GetImpl().(*Step_DockerBuild); ok {
		return x.DockerBuild
	}
	return nil
}

func (m *Step) GetDockerCompose() *DockerCompose {
	if x, ok := m.GetImpl().(*Step_DockerCompose); ok {
		return x.DockerCompose
	}
	return nil
}

func (m *Step) GetDockerPush() *DockerPush {
	if x, ok := m.GetImpl().(*Step_DockerPush); ok {
		return x.DockerPush
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Step) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Step_Setup)(nil),
		(*Step_DockerRun)(nil),
		(*Step_DockerBuild)(nil),
		(*Step_DockerCompose)(nil),
		(*Step_DockerPush)(nil),
	}
}

type Stream struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stream) Reset()         { *m = Stream{} }
func (m *Stream) String() string { return proto.CompactTextString(m) }
func (*Stream) ProtoMessage()    {}
func (*Stream) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3716d53a7e1b752, []int{1}
}

func (m *Stream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stream.Unmarshal(m, b)
}
func (m *Stream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stream.Marshal(b, m, deterministic)
}
func (m *Stream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stream.Merge(m, src)
}
func (m *Stream) XXX_Size() int {
	return xxx_messageInfo_Stream.Size(m)
}
func (m *Stream) XXX_DiscardUnknown() {
	xxx_messageInfo_Stream.DiscardUnknown(m)
}

var xxx_messageInfo_Stream proto.InternalMessageInfo

func (m *Stream) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Stream) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Stream) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type Setup struct {
	Repository           *Repository `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	Branch               string      `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	CommitHash           string      `protobuf:"bytes,3,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Setup) Reset()         { *m = Setup{} }
func (m *Setup) String() string { return proto.CompactTextString(m) }
func (*Setup) ProtoMessage()    {}
func (*Setup) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3716d53a7e1b752, []int{2}
}

func (m *Setup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Setup.Unmarshal(m, b)
}
func (m *Setup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Setup.Marshal(b, m, deterministic)
}
func (m *Setup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Setup.Merge(m, src)
}
func (m *Setup) XXX_Size() int {
	return xxx_messageInfo_Setup.Size(m)
}
func (m *Setup) XXX_DiscardUnknown() {
	xxx_messageInfo_Setup.DiscardUnknown(m)
}

var xxx_messageInfo_Setup proto.InternalMessageInfo

func (m *Setup) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

func (m *Setup) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *Setup) GetCommitHash() string {
	if m != nil {
		return m.CommitHash
	}
	return ""
}

type DockerRun struct {
	Image                string   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Command              string   `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Environment          string   `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	WorkingDir           string   `protobuf:"bytes,4,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	MountPoint           string   `protobuf:"bytes,5,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	IgnoreExitCode       string   `protobuf:"bytes,6,opt,name=ignore_exit_code,json=ignoreExitCode,proto3" json:"ignore_exit_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DockerRun) Reset()         { *m = DockerRun{} }
func (m *DockerRun) String() string { return proto.CompactTextString(m) }
func (*DockerRun) ProtoMessage()    {}
func (*DockerRun) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3716d53a7e1b752, []int{3}
}

func (m *DockerRun) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DockerRun.Unmarshal(m, b)
}
func (m *DockerRun) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DockerRun.Marshal(b, m, deterministic)
}
func (m *DockerRun) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DockerRun.Merge(m, src)
}
func (m *DockerRun) XXX_Size() int {
	return xxx_messageInfo_DockerRun.Size(m)
}
func (m *DockerRun) XXX_DiscardUnknown() {
	xxx_messageInfo_DockerRun.DiscardUnknown(m)
}

var xxx_messageInfo_DockerRun proto.InternalMessageInfo

func (m *DockerRun) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *DockerRun) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *DockerRun) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

func (m *DockerRun) GetWorkingDir() string {
	if m != nil {
		return m.WorkingDir
	}
	return ""
}

func (m *DockerRun) GetMountPoint() string {
	if m != nil {
		return m.MountPoint
	}
	return ""
}

func (m *DockerRun) GetIgnoreExitCode() string {
	if m != nil {
		return m.IgnoreExitCode
	}
	return ""
}

type DockerBuild struct {
	Dockerfile           string   `protobuf:"bytes,1,opt,name=dockerfile,proto3" json:"dockerfile,omitempty"`
	Context              string   `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	Tags                 []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DockerBuild) Reset()         { *m = DockerBuild{} }
func (m *DockerBuild) String() string { return proto.CompactTextString(m) }
func (*DockerBuild) ProtoMessage()    {}
func (*DockerBuild) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3716d53a7e1b752, []int{4}
}

func (m *DockerBuild) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DockerBuild.Unmarshal(m, b)
}
func (m *DockerBuild) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DockerBuild.Marshal(b, m, deterministic)
}
func (m *DockerBuild) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DockerBuild.Merge(m, src)
}
func (m *DockerBuild) XXX_Size() int {
	return xxx_messageInfo_DockerBuild.Size(m)
}
func (m *DockerBuild) XXX_DiscardUnknown() {
	xxx_messageInfo_DockerBuild.DiscardUnknown(m)
}

var xxx_messageInfo_DockerBuild proto.InternalMessageInfo

func (m *DockerBuild) GetDockerfile() string {
	if m != nil {
		return m.Dockerfile
	}
	return ""
}

func (m *DockerBuild) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *DockerBuild) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type DockerCompose struct {
	ComposeFile          string   `protobuf:"bytes,1,opt,name=compose_file,json=composeFile,proto3" json:"compose_file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DockerCompose) Reset()         { *m = DockerCompose{} }
func (m *DockerCompose) String() string { return proto.CompactTextString(m) }
func (*DockerCompose) ProtoMessage()    {}
func (*DockerCompose) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3716d53a7e1b752, []int{5}
}

func (m *DockerCompose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DockerCompose.Unmarshal(m, b)
}
func (m *DockerCompose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DockerCompose.Marshal(b, m, deterministic)
}
func (m *DockerCompose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DockerCompose.Merge(m, src)
}
func (m *DockerCompose) XXX_Size() int {
	return xxx_messageInfo_DockerCompose.Size(m)
}
func (m *DockerCompose) XXX_DiscardUnknown() {
	xxx_messageInfo_DockerCompose.DiscardUnknown(m)
}

var xxx_messageInfo_DockerCompose proto.InternalMessageInfo

func (m *DockerCompose) GetComposeFile() string {
	if m != nil {
		return m.ComposeFile
	}
	return ""
}

type DockerPush struct {
	Tags                 []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DockerPush) Reset()         { *m = DockerPush{} }
func (m *DockerPush) String() string { return proto.CompactTextString(m) }
func (*DockerPush) ProtoMessage()    {}
func (*DockerPush) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3716d53a7e1b752, []int{6}
}

func (m *DockerPush) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DockerPush.Unmarshal(m, b)
}
func (m *DockerPush) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DockerPush.Marshal(b, m, deterministic)
}
func (m *DockerPush) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DockerPush.Merge(m, src)
}
func (m *DockerPush) XXX_Size() int {
	return xxx_messageInfo_DockerPush.Size(m)
}
func (m *DockerPush) XXX_DiscardUnknown() {
	xxx_messageInfo_DockerPush.DiscardUnknown(m)
}

var xxx_messageInfo_DockerPush proto.InternalMessageInfo

func (m *DockerPush) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterType((*Step)(nil), "velocity.v1.Step")
	proto.RegisterType((*Stream)(nil), "velocity.v1.Stream")
	proto.RegisterType((*Setup)(nil), "velocity.v1.Setup")
	proto.RegisterType((*DockerRun)(nil), "velocity.v1.DockerRun")
	proto.RegisterType((*DockerBuild)(nil), "velocity.v1.DockerBuild")
	proto.RegisterType((*DockerCompose)(nil), "velocity.v1.DockerCompose")
	proto.RegisterType((*DockerPush)(nil), "velocity.v1.DockerPush")
}

func init() { proto.RegisterFile("step.proto", fileDescriptor_d3716d53a7e1b752) }

var fileDescriptor_d3716d53a7e1b752 = []byte{
	// 601 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xcd, 0x6e, 0xdb, 0x3c,
	0x10, 0xb4, 0x1d, 0xdb, 0x81, 0x56, 0x49, 0x10, 0xf0, 0xfb, 0x90, 0x0a, 0x39, 0x34, 0xae, 0x4e,
	0x46, 0x81, 0x2a, 0x48, 0x7a, 0x28, 0x5a, 0xa0, 0x87, 0xfc, 0xb4, 0xf0, 0x31, 0x60, 0x7a, 0x6a,
	0x0f, 0x02, 0x2d, 0x32, 0x12, 0x11, 0x8b, 0x14, 0xc8, 0x95, 0x9b, 0xbc, 0x4e, 0xdf, 0xa6, 0x6f,
	0x55, 0x88, 0xa2, 0x62, 0xb9, 0x09, 0xd0, 0x9b, 0x76, 0x76, 0x67, 0xc8, 0xd1, 0x0e, 0x01, 0x2c,
	0x8a, 0x2a, 0xa9, 0x8c, 0x46, 0x4d, 0xc2, 0xb5, 0x58, 0xe9, 0x4c, 0xe2, 0x63, 0xb2, 0x3e, 0x3b,
	0x3e, 0xc9, 0xb5, 0xce, 0x57, 0xe2, 0xd4, 0xb5, 0x96, 0xf5, 0xdd, 0x29, 0xca, 0x52, 0x58, 0x64,
	0xa5, 0x9f, 0x3e, 0x3e, 0x34, 0xa2, 0xd2, 0x56, 0xa2, 0x36, 0x8f, 0x2d, 0x12, 0xff, 0x1a, 0xc3,
	0xf8, 0x16, 0x45, 0x45, 0x0e, 0x60, 0x24, 0x79, 0x34, 0x9c, 0x0d, 0xe7, 0x01, 0x1d, 0x49, 0x4e,
	0x66, 0x10, 0x72, 0x61, 0x33, 0x23, 0x2b, 0x94, 0x5a, 0x45, 0x23, 0xd7, 0xe8, 0x43, 0xe4, 0x1d,
	0xec, 0x5a, 0x34, 0x82, 0x95, 0x36, 0xda, 0x99, 0xed, 0xcc, 0xc3, 0xf3, 0xff, 0x92, 0xde, 0x65,
	0x92, 0x5b, 0xd7, 0xa3, 0xdd, 0x0c, 0x39, 0x82, 0xa9, 0x45, 0x86, 0xb5, 0x8d, 0xc6, 0x4e, 0xcb,
	0x57, 0xe4, 0x63, 0xe3, 0x87, 0x19, 0x14, 0x3c, 0x65, 0x18, 0x4d, 0x66, 0xc3, 0x79, 0x78, 0x7e,
	0x9c, 0xb4, 0x4e, 0x92, 0xce, 0x49, 0xf2, 0xad, 0x73, 0x42, 0x03, 0x3f, 0x7d, 0x81, 0x0d, 0xb5,
	0xae, 0x38, 0xf3, 0xd4, 0xe9, 0xbf, 0xa9, 0x7e, 0xfa, 0x02, 0xc9, 0x5b, 0x98, 0x58, 0x81, 0x75,
	0x15, 0x71, 0xc7, 0x22, 0xdb, 0x57, 0x6f, 0x3a, 0x8b, 0x01, 0x6d, 0x47, 0xc8, 0x07, 0x00, 0xae,
	0xb3, 0x7b, 0x61, 0x52, 0x53, 0xab, 0x48, 0x38, 0xc2, 0xd1, 0x16, 0xe1, 0xda, 0xb5, 0x69, 0xad,
	0x16, 0x03, 0x1a, 0xf0, 0xae, 0x20, 0x9f, 0x61, 0xcf, 0x13, 0x97, 0xb5, 0x5c, 0xf1, 0xe8, 0xce,
	0x51, 0xa3, 0x17, 0xa8, 0x97, 0x4d, 0x7f, 0x31, 0xa0, 0x21, 0xdf, 0x94, 0xe4, 0x0a, 0x0e, 0x3c,
	0x3d, 0xd3, 0x65, 0xa5, 0xad, 0x88, 0x72, 0x6f, 0xf1, 0xb9, 0xc0, 0x55, 0x3b, 0xb1, 0x18, 0xd0,
	0x7d, 0xde, 0x07, 0xc8, 0x27, 0xf0, 0x9a, 0x69, 0x55, 0xdb, 0x22, 0x2a, 0x9c, 0xc2, 0xab, 0x17,
	0x14, 0x6e, 0x6a, 0x5b, 0x2c, 0x06, 0xd4, 0x5b, 0x6d, 0xaa, 0xcb, 0x29, 0x8c, 0x65, 0x59, 0xad,
	0xe2, 0x6b, 0x98, 0xb6, 0xdb, 0x7c, 0x96, 0x12, 0x02, 0x63, 0xc5, 0x4a, 0xe1, 0xe3, 0xe1, 0xbe,
	0x7b, 0x8b, 0xde, 0xe9, 0x2f, 0x3a, 0x7e, 0x84, 0xc9, 0x6d, 0xf7, 0x3f, 0x37, 0x39, 0x74, 0x62,
	0x7f, 0xdf, 0x88, 0x3e, 0xb5, 0x69, 0x6f, 0xb4, 0x51, 0x5e, 0x1a, 0xa6, 0xb2, 0xc2, 0x9f, 0xe7,
	0x2b, 0x72, 0x02, 0x61, 0xa6, 0xcb, 0x52, 0x62, 0x5a, 0x30, 0x5b, 0xf8, 0x63, 0xa1, 0x85, 0x16,
	0xcc, 0x16, 0xf1, 0xef, 0x21, 0x04, 0x4f, 0x3b, 0x22, 0xff, 0xc3, 0x44, 0x96, 0x2c, 0x17, 0xde,
	0x47, 0x5b, 0x90, 0x08, 0x76, 0x1b, 0x06, 0x53, 0xdc, 0xab, 0x77, 0x65, 0xf3, 0x14, 0x84, 0x5a,
	0x4b, 0xa3, 0x55, 0x29, 0x14, 0x7a, 0xf9, 0x3e, 0xd4, 0x5c, 0xe0, 0xa7, 0x36, 0xf7, 0x52, 0xe5,
	0x29, 0x97, 0xc6, 0x07, 0x1c, 0x3c, 0x74, 0x2d, 0x4d, 0x33, 0x50, 0xea, 0x5a, 0x61, 0x5a, 0x69,
	0xa9, 0xda, 0x94, 0x07, 0x14, 0x1c, 0x74, 0xd3, 0x20, 0x64, 0x0e, 0x87, 0x32, 0x57, 0xda, 0x88,
	0x54, 0x3c, 0x48, 0x4c, 0x33, 0xcd, 0x85, 0x0b, 0x74, 0x40, 0x0f, 0x5a, 0xfc, 0xcb, 0x83, 0xc4,
	0x2b, 0xcd, 0x45, 0xfc, 0x03, 0xc2, 0x5e, 0x66, 0xc8, 0xeb, 0x2e, 0x9c, 0x77, 0x72, 0xd5, 0x39,
	0xea, 0x21, 0xad, 0x2d, 0x85, 0xe2, 0x01, 0x37, 0xb6, 0x5c, 0xd9, 0xec, 0x0e, 0x59, 0xde, 0x3e,
	0xde, 0x80, 0xba, 0xef, 0xf8, 0x1c, 0xf6, 0xb7, 0xf2, 0x44, 0xde, 0xc0, 0x9e, 0x0f, 0x5f, 0xda,
	0x3b, 0x20, 0xf4, 0xd8, 0x57, 0xb9, 0x12, 0xf1, 0x0c, 0x60, 0x93, 0xa0, 0x27, 0xd5, 0xe1, 0x46,
	0xf5, 0x72, 0xfc, 0x7d, 0xb4, 0x3e, 0x5b, 0x4e, 0xdd, 0x8b, 0x7c, 0xff, 0x27, 0x00, 0x00, 0xff,
	0xff, 0x19, 0xe7, 0xc9, 0x90, 0xbf, 0x04, 0x00, 0x00,
}
