// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stream.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Stream struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ActionId             string               `protobuf:"bytes,2,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Status               string               `protobuf:"bytes,20,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt            *timestamp.Timestamp `protobuf:"bytes,21,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,22,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Stream) Reset()         { *m = Stream{} }
func (m *Stream) String() string { return proto.CompactTextString(m) }
func (*Stream) ProtoMessage()    {}
func (*Stream) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{0}
}

func (m *Stream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stream.Unmarshal(m, b)
}
func (m *Stream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stream.Marshal(b, m, deterministic)
}
func (m *Stream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stream.Merge(m, src)
}
func (m *Stream) XXX_Size() int {
	return xxx_messageInfo_Stream.Size(m)
}
func (m *Stream) XXX_DiscardUnknown() {
	xxx_messageInfo_Stream.DiscardUnknown(m)
}

var xxx_messageInfo_Stream proto.InternalMessageInfo

func (m *Stream) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Stream) GetActionId() string {
	if m != nil {
		return m.ActionId
	}
	return ""
}

func (m *Stream) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Stream) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Stream) GetStartedAt() *timestamp.Timestamp {
	if m != nil {
		return m.StartedAt
	}
	return nil
}

func (m *Stream) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*Stream)(nil), "velocity.v1.Stream")
}

func init() { proto.RegisterFile("stream.proto", fileDescriptor_bb17ef3f514bfe54) }

var fileDescriptor_bb17ef3f514bfe54 = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8e, 0xb1, 0x4b, 0xc4, 0x30,
	0x14, 0x87, 0x49, 0x3c, 0x8a, 0x7d, 0x27, 0x0e, 0x41, 0x8f, 0x70, 0x0e, 0x1e, 0x4e, 0x37, 0xe5,
	0x38, 0x9d, 0x1c, 0xeb, 0xe6, 0x5a, 0x9d, 0x5c, 0xca, 0x6b, 0x13, 0x4b, 0xa0, 0x69, 0x4a, 0xf3,
	0x5a, 0xf0, 0x2f, 0xf5, 0xdf, 0x11, 0xd3, 0x74, 0xbe, 0x2d, 0xf9, 0xde, 0xf7, 0xc1, 0x0f, 0x6e,
	0x02, 0x8d, 0x06, 0x9d, 0x1a, 0x46, 0x4f, 0x5e, 0x6c, 0x67, 0xd3, 0xf9, 0xc6, 0xd2, 0x8f, 0x9a,
	0xcf, 0xfb, 0xc7, 0xd6, 0xfb, 0xb6, 0x33, 0xa7, 0x78, 0xaa, 0xa7, 0xef, 0x13, 0x59, 0x67, 0x02,
	0xa1, 0x1b, 0x16, 0xfb, 0xe9, 0x97, 0x41, 0xf6, 0x11, 0x73, 0x71, 0x0b, 0xdc, 0x6a, 0xc9, 0x0e,
	0xec, 0x98, 0x97, 0xdc, 0x6a, 0xf1, 0x00, 0x39, 0x36, 0x64, 0x7d, 0x5f, 0x59, 0x2d, 0x79, 0xc4,
	0xd7, 0x0b, 0x78, 0xd7, 0x42, 0xc0, 0xa6, 0x47, 0x67, 0xe4, 0x55, 0xe4, 0xf1, 0x2d, 0x76, 0x90,
	0x05, 0x42, 0x9a, 0x82, 0xbc, 0x8b, 0x34, 0xfd, 0xc4, 0x2b, 0x40, 0x20, 0x1c, 0xc9, 0xe8, 0x0a,
	0x49, 0xde, 0x1f, 0xd8, 0x71, 0xfb, 0xbc, 0x57, 0xcb, 0x32, 0xb5, 0x2e, 0x53, 0x9f, 0xeb, 0xb2,
	0x32, 0x4f, 0x76, 0x41, 0xff, 0xe9, 0x34, 0x68, 0x4c, 0xe9, 0xee, 0x72, 0x9a, 0xec, 0x82, 0xde,
	0x36, 0x5f, 0x7c, 0x3e, 0xd7, 0x59, 0x94, 0x5e, 0xfe, 0x02, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x65,
	0xb3, 0x9c, 0x24, 0x01, 0x00, 0x00,
}
