// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Task struct {
	Id                   string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Parameters           map[string]*TaskParameter `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Blueprint            string                    `protobuf:"bytes,3,opt,name=blueprint,proto3" json:"blueprint,omitempty"`
	IgnoreErrors         bool                      `protobuf:"varint,4,opt,name=ignore_errors,json=ignoreErrors,proto3" json:"ignore_errors,omitempty"`
	Actions              []*Action                 `protobuf:"bytes,5,rep,name=actions,proto3" json:"actions,omitempty"`
	Status               string                    `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt            *timestamp.Timestamp      `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp      `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Task) GetParameters() map[string]*TaskParameter {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *Task) GetBlueprint() string {
	if m != nil {
		return m.Blueprint
	}
	return ""
}

func (m *Task) GetIgnoreErrors() bool {
	if m != nil {
		return m.IgnoreErrors
	}
	return false
}

func (m *Task) GetActions() []*Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *Task) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Task) GetStartedAt() *timestamp.Timestamp {
	if m != nil {
		return m.StartedAt
	}
	return nil
}

func (m *Task) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type TaskParameter struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Secret               bool     `protobuf:"varint,3,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskParameter) Reset()         { *m = TaskParameter{} }
func (m *TaskParameter) String() string { return proto.CompactTextString(m) }
func (*TaskParameter) ProtoMessage()    {}
func (*TaskParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{1}
}

func (m *TaskParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskParameter.Unmarshal(m, b)
}
func (m *TaskParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskParameter.Marshal(b, m, deterministic)
}
func (m *TaskParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskParameter.Merge(m, src)
}
func (m *TaskParameter) XXX_Size() int {
	return xxx_messageInfo_TaskParameter.Size(m)
}
func (m *TaskParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskParameter.DiscardUnknown(m)
}

var xxx_messageInfo_TaskParameter proto.InternalMessageInfo

func (m *TaskParameter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TaskParameter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *TaskParameter) GetSecret() bool {
	if m != nil {
		return m.Secret
	}
	return false
}

type TaskDocker struct {
	Registries           []*TaskDockerRegistry `protobuf:"bytes,1,rep,name=registries,proto3" json:"registries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TaskDocker) Reset()         { *m = TaskDocker{} }
func (m *TaskDocker) String() string { return proto.CompactTextString(m) }
func (*TaskDocker) ProtoMessage()    {}
func (*TaskDocker) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{2}
}

func (m *TaskDocker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskDocker.Unmarshal(m, b)
}
func (m *TaskDocker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskDocker.Marshal(b, m, deterministic)
}
func (m *TaskDocker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskDocker.Merge(m, src)
}
func (m *TaskDocker) XXX_Size() int {
	return xxx_messageInfo_TaskDocker.Size(m)
}
func (m *TaskDocker) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskDocker.DiscardUnknown(m)
}

var xxx_messageInfo_TaskDocker proto.InternalMessageInfo

func (m *TaskDocker) GetRegistries() []*TaskDockerRegistry {
	if m != nil {
		return m.Registries
	}
	return nil
}

type TaskDockerRegistry struct {
	Registry             *DockerRegistry `protobuf:"bytes,1,opt,name=registry,proto3" json:"registry,omitempty"`
	AuthorizationToken   string          `protobuf:"bytes,2,opt,name=authorization_token,json=authorizationToken,proto3" json:"authorization_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TaskDockerRegistry) Reset()         { *m = TaskDockerRegistry{} }
func (m *TaskDockerRegistry) String() string { return proto.CompactTextString(m) }
func (*TaskDockerRegistry) ProtoMessage()    {}
func (*TaskDockerRegistry) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{3}
}

func (m *TaskDockerRegistry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskDockerRegistry.Unmarshal(m, b)
}
func (m *TaskDockerRegistry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskDockerRegistry.Marshal(b, m, deterministic)
}
func (m *TaskDockerRegistry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskDockerRegistry.Merge(m, src)
}
func (m *TaskDockerRegistry) XXX_Size() int {
	return xxx_messageInfo_TaskDockerRegistry.Size(m)
}
func (m *TaskDockerRegistry) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskDockerRegistry.DiscardUnknown(m)
}

var xxx_messageInfo_TaskDockerRegistry proto.InternalMessageInfo

func (m *TaskDockerRegistry) GetRegistry() *DockerRegistry {
	if m != nil {
		return m.Registry
	}
	return nil
}

func (m *TaskDockerRegistry) GetAuthorizationToken() string {
	if m != nil {
		return m.AuthorizationToken
	}
	return ""
}

func init() {
	proto.RegisterType((*Task)(nil), "velocity.v1.Task")
	proto.RegisterMapType((map[string]*TaskParameter)(nil), "velocity.v1.Task.ParametersEntry")
	proto.RegisterType((*TaskParameter)(nil), "velocity.v1.TaskParameter")
	proto.RegisterType((*TaskDocker)(nil), "velocity.v1.TaskDocker")
	proto.RegisterType((*TaskDockerRegistry)(nil), "velocity.v1.TaskDockerRegistry")
}

func init() { proto.RegisterFile("task.proto", fileDescriptor_ce5d8dd45b4a91ff) }

var fileDescriptor_ce5d8dd45b4a91ff = []byte{
	// 441 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x4f, 0x8f, 0x12, 0x41,
	0x10, 0xc5, 0x33, 0x03, 0xcb, 0x42, 0xb1, 0xeb, 0x9a, 0x5a, 0x63, 0x3a, 0x68, 0xb2, 0x88, 0x17,
	0x2e, 0x0e, 0x2e, 0x1e, 0xfc, 0x73, 0x31, 0x18, 0xf7, 0x68, 0xa2, 0x1d, 0x2e, 0x7a, 0x21, 0x0d,
	0x94, 0xd8, 0x01, 0xa6, 0x27, 0xdd, 0x35, 0x24, 0x78, 0xf0, 0x53, 0xf9, 0x01, 0xcd, 0x74, 0x37,
	0x08, 0xec, 0x61, 0x6f, 0xdd, 0x55, 0xbf, 0xf7, 0xba, 0xfa, 0x15, 0x00, 0x2b, 0xb7, 0xcc, 0x0a,
	0x6b, 0xd8, 0x60, 0x7b, 0x43, 0x2b, 0x33, 0xd3, 0xbc, 0xcd, 0x36, 0xb7, 0x9d, 0x0b, 0x35, 0x63,
	0x6d, 0xf2, 0xd0, 0xea, 0x5c, 0x4d, 0x57, 0x25, 0x15, 0x56, 0xe7, 0x1c, 0x0b, 0x37, 0x0b, 0x63,
	0x16, 0x2b, 0x1a, 0xf8, 0xdb, 0xb4, 0xfc, 0x39, 0x60, 0xbd, 0x26, 0xc7, 0x6a, 0x5d, 0x04, 0xa0,
	0xf7, 0xb7, 0x06, 0xf5, 0xb1, 0x72, 0x4b, 0x7c, 0x04, 0xa9, 0x9e, 0x8b, 0xa4, 0x9b, 0xf4, 0x5b,
	0x32, 0xd5, 0x73, 0x1c, 0x01, 0x14, 0xca, 0xaa, 0x35, 0x31, 0x59, 0x27, 0xd2, 0x6e, 0xad, 0xdf,
	0x1e, 0xbe, 0xc8, 0x0e, 0x9e, 0xce, 0x2a, 0x59, 0xf6, 0x75, 0xcf, 0xdc, 0xe5, 0x6c, 0xb7, 0xf2,
	0x40, 0x84, 0xcf, 0xa1, 0xb5, 0x9f, 0x47, 0xd4, 0xbc, 0xf3, 0xff, 0x02, 0xbe, 0x84, 0x4b, 0xbd,
	0xc8, 0x8d, 0xa5, 0x09, 0x59, 0x6b, 0xac, 0x13, 0xf5, 0x6e, 0xd2, 0x6f, 0xca, 0x8b, 0x50, 0xbc,
	0xf3, 0x35, 0x7c, 0x05, 0xe7, 0xe1, 0x83, 0x4e, 0x9c, 0xf9, 0x11, 0xae, 0x8f, 0x46, 0x18, 0xf9,
	0x9e, 0xdc, 0x31, 0xf8, 0x14, 0x1a, 0x8e, 0x15, 0x97, 0x4e, 0x34, 0xfc, 0x73, 0xf1, 0x86, 0xef,
	0x01, 0x1c, 0x2b, 0xcb, 0x34, 0x9f, 0x28, 0x16, 0xe7, 0xdd, 0xa4, 0xdf, 0x1e, 0x76, 0xb2, 0x90,
	0x4d, 0xb6, 0xcb, 0x26, 0x1b, 0xef, 0xb2, 0x91, 0xad, 0x48, 0x8f, 0xb8, 0x92, 0x96, 0xc5, 0x5c,
	0x45, 0x69, 0xf3, 0x61, 0x69, 0xa4, 0x47, 0xdc, 0xf9, 0x0e, 0x57, 0x27, 0xf1, 0xe0, 0x63, 0xa8,
	0x2d, 0x69, 0x1b, 0x63, 0xae, 0x8e, 0xf8, 0x1a, 0xce, 0x36, 0x6a, 0x55, 0x92, 0x48, 0xa3, 0xf5,
	0x69, 0xc4, 0x7b, 0x0b, 0x19, 0xc0, 0x0f, 0xe9, 0xbb, 0xa4, 0xf7, 0x0d, 0x2e, 0x8f, 0x7a, 0x88,
	0x50, 0xcf, 0xd5, 0x9a, 0xa2, 0xb3, 0x3f, 0xe3, 0x93, 0x43, 0xeb, 0x56, 0x94, 0xfb, 0x8c, 0x68,
	0x66, 0x29, 0xac, 0xa4, 0x29, 0xe3, 0xad, 0xf7, 0x05, 0xa0, 0xb2, 0xfc, 0x6c, 0x66, 0x4b, 0xb2,
	0xf8, 0x11, 0xc0, 0xd2, 0x42, 0x3b, 0xb6, 0x9a, 0x9c, 0x48, 0x7c, 0xf6, 0x37, 0xf7, 0x66, 0x0b,
	0xb0, 0x0c, 0xe0, 0x56, 0x1e, 0x48, 0x7a, 0x7f, 0x00, 0xef, 0x13, 0xf8, 0x16, 0x9a, 0x91, 0x09,
	0x21, 0xb4, 0x87, 0xcf, 0x8e, 0x4c, 0x4f, 0x0c, 0xf7, 0x30, 0x0e, 0xe0, 0x5a, 0x95, 0xfc, 0xcb,
	0x58, 0xfd, 0x5b, 0x55, 0xbb, 0x9e, 0xb0, 0x59, 0x52, 0x1e, 0x7f, 0x86, 0x47, 0xad, 0x71, 0xd5,
	0xf9, 0x54, 0xff, 0x91, 0x6e, 0x6e, 0xa7, 0x0d, 0xbf, 0xa1, 0x37, 0xff, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x09, 0xd4, 0x8c, 0x61, 0x40, 0x03, 0x00, 0x00,
}
