// Code generated by protoc-gen-go. DO NOT EDIT.
// source: velocity.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RepoQuery_RepoType int32

const (
	RepoQuery_HEAD   RepoQuery_RepoType = 0
	RepoQuery_COMMIT RepoQuery_RepoType = 1
)

var RepoQuery_RepoType_name = map[int32]string{
	0: "HEAD",
	1: "COMMIT",
}

var RepoQuery_RepoType_value = map[string]int32{
	"HEAD":   0,
	"COMMIT": 1,
}

func (x RepoQuery_RepoType) String() string {
	return proto.EnumName(RepoQuery_RepoType_name, int32(x))
}

func (RepoQuery_RepoType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9d28a901b1212a72, []int{6, 0}
}

type Project struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string               `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d28a901b1212a72, []int{0}
}

func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Project) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Project) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type CreateProjectRequest struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Repository           *Repository `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateProjectRequest) Reset()         { *m = CreateProjectRequest{} }
func (m *CreateProjectRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProjectRequest) ProtoMessage()    {}
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d28a901b1212a72, []int{1}
}

func (m *CreateProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectRequest.Unmarshal(m, b)
}
func (m *CreateProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectRequest.Marshal(b, m, deterministic)
}
func (m *CreateProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectRequest.Merge(m, src)
}
func (m *CreateProjectRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProjectRequest.Size(m)
}
func (m *CreateProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectRequest proto.InternalMessageInfo

func (m *CreateProjectRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateProjectRequest) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

type GetProjectRequest struct {
	// The id of the project in the form of
	// `[PROJECT_ID]`.
	ProjectId            string   `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProjectRequest) Reset()         { *m = GetProjectRequest{} }
func (m *GetProjectRequest) String() string { return proto.CompactTextString(m) }
func (*GetProjectRequest) ProtoMessage()    {}
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d28a901b1212a72, []int{2}
}

func (m *GetProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectRequest.Unmarshal(m, b)
}
func (m *GetProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectRequest.Marshal(b, m, deterministic)
}
func (m *GetProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectRequest.Merge(m, src)
}
func (m *GetProjectRequest) XXX_Size() int {
	return xxx_messageInfo_GetProjectRequest.Size(m)
}
func (m *GetProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectRequest proto.InternalMessageInfo

func (m *GetProjectRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type ListProjectsRequest struct {
	Ids                  []string   `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Names                []string   `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	PageQuery            *PageQuery `protobuf:"bytes,99,opt,name=page_query,json=pageQuery,proto3" json:"page_query,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListProjectsRequest) Reset()         { *m = ListProjectsRequest{} }
func (m *ListProjectsRequest) String() string { return proto.CompactTextString(m) }
func (*ListProjectsRequest) ProtoMessage()    {}
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d28a901b1212a72, []int{3}
}

func (m *ListProjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProjectsRequest.Unmarshal(m, b)
}
func (m *ListProjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProjectsRequest.Marshal(b, m, deterministic)
}
func (m *ListProjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProjectsRequest.Merge(m, src)
}
func (m *ListProjectsRequest) XXX_Size() int {
	return xxx_messageInfo_ListProjectsRequest.Size(m)
}
func (m *ListProjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListProjectsRequest proto.InternalMessageInfo

func (m *ListProjectsRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *ListProjectsRequest) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *ListProjectsRequest) GetPageQuery() *PageQuery {
	if m != nil {
		return m.PageQuery
	}
	return nil
}

type ListProjectsResponse struct {
	Projects             []*Project `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListProjectsResponse) Reset()         { *m = ListProjectsResponse{} }
func (m *ListProjectsResponse) String() string { return proto.CompactTextString(m) }
func (*ListProjectsResponse) ProtoMessage()    {}
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d28a901b1212a72, []int{4}
}

func (m *ListProjectsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProjectsResponse.Unmarshal(m, b)
}
func (m *ListProjectsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProjectsResponse.Marshal(b, m, deterministic)
}
func (m *ListProjectsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProjectsResponse.Merge(m, src)
}
func (m *ListProjectsResponse) XXX_Size() int {
	return xxx_messageInfo_ListProjectsResponse.Size(m)
}
func (m *ListProjectsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProjectsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListProjectsResponse proto.InternalMessageInfo

func (m *ListProjectsResponse) GetProjects() []*Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

type PageQuery struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Skip                 int32    `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageQuery) Reset()         { *m = PageQuery{} }
func (m *PageQuery) String() string { return proto.CompactTextString(m) }
func (*PageQuery) ProtoMessage()    {}
func (*PageQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d28a901b1212a72, []int{5}
}

func (m *PageQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageQuery.Unmarshal(m, b)
}
func (m *PageQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageQuery.Marshal(b, m, deterministic)
}
func (m *PageQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageQuery.Merge(m, src)
}
func (m *PageQuery) XXX_Size() int {
	return xxx_messageInfo_PageQuery.Size(m)
}
func (m *PageQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_PageQuery.DiscardUnknown(m)
}

var xxx_messageInfo_PageQuery proto.InternalMessageInfo

func (m *PageQuery) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *PageQuery) GetSkip() int32 {
	if m != nil {
		return m.Skip
	}
	return 0
}

type RepoQuery struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepoQuery) Reset()         { *m = RepoQuery{} }
func (m *RepoQuery) String() string { return proto.CompactTextString(m) }
func (*RepoQuery) ProtoMessage()    {}
func (*RepoQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d28a901b1212a72, []int{6}
}

func (m *RepoQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepoQuery.Unmarshal(m, b)
}
func (m *RepoQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepoQuery.Marshal(b, m, deterministic)
}
func (m *RepoQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepoQuery.Merge(m, src)
}
func (m *RepoQuery) XXX_Size() int {
	return xxx_messageInfo_RepoQuery.Size(m)
}
func (m *RepoQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_RepoQuery.DiscardUnknown(m)
}

var xxx_messageInfo_RepoQuery proto.InternalMessageInfo

func (m *RepoQuery) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type BlueprintQuery struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlueprintQuery) Reset()         { *m = BlueprintQuery{} }
func (m *BlueprintQuery) String() string { return proto.CompactTextString(m) }
func (*BlueprintQuery) ProtoMessage()    {}
func (*BlueprintQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d28a901b1212a72, []int{7}
}

func (m *BlueprintQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlueprintQuery.Unmarshal(m, b)
}
func (m *BlueprintQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlueprintQuery.Marshal(b, m, deterministic)
}
func (m *BlueprintQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlueprintQuery.Merge(m, src)
}
func (m *BlueprintQuery) XXX_Size() int {
	return xxx_messageInfo_BlueprintQuery.Size(m)
}
func (m *BlueprintQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_BlueprintQuery.DiscardUnknown(m)
}

var xxx_messageInfo_BlueprintQuery proto.InternalMessageInfo

func (m *BlueprintQuery) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type Blueprint struct {
	// BLUEPRINT_ID = commit_sha+blueprint_name
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CommitId             string   `protobuf:"bytes,2,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blueprint) Reset()         { *m = Blueprint{} }
func (m *Blueprint) String() string { return proto.CompactTextString(m) }
func (*Blueprint) ProtoMessage()    {}
func (*Blueprint) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d28a901b1212a72, []int{8}
}

func (m *Blueprint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blueprint.Unmarshal(m, b)
}
func (m *Blueprint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blueprint.Marshal(b, m, deterministic)
}
func (m *Blueprint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blueprint.Merge(m, src)
}
func (m *Blueprint) XXX_Size() int {
	return xxx_messageInfo_Blueprint.Size(m)
}
func (m *Blueprint) XXX_DiscardUnknown() {
	xxx_messageInfo_Blueprint.DiscardUnknown(m)
}

var xxx_messageInfo_Blueprint proto.InternalMessageInfo

func (m *Blueprint) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Blueprint) GetCommitId() string {
	if m != nil {
		return m.CommitId
	}
	return ""
}

type GetBlueprintRequest struct {
	// The id of the project in the form of
	// `[PROJECT_ID]`.
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// The id of the blueprint in the form of
	// `[BLUEPRINT_ID]`.
	BlueprintId          string   `protobuf:"bytes,2,opt,name=blueprint_id,json=blueprintId,proto3" json:"blueprint_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlueprintRequest) Reset()         { *m = GetBlueprintRequest{} }
func (m *GetBlueprintRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlueprintRequest) ProtoMessage()    {}
func (*GetBlueprintRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d28a901b1212a72, []int{9}
}

func (m *GetBlueprintRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlueprintRequest.Unmarshal(m, b)
}
func (m *GetBlueprintRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlueprintRequest.Marshal(b, m, deterministic)
}
func (m *GetBlueprintRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlueprintRequest.Merge(m, src)
}
func (m *GetBlueprintRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlueprintRequest.Size(m)
}
func (m *GetBlueprintRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlueprintRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlueprintRequest proto.InternalMessageInfo

func (m *GetBlueprintRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *GetBlueprintRequest) GetBlueprintId() string {
	if m != nil {
		return m.BlueprintId
	}
	return ""
}

type ListBlueprintsRequest struct {
	RepoQuery            *RepoQuery `protobuf:"bytes,1,opt,name=repo_query,json=repoQuery,proto3" json:"repo_query,omitempty"`
	PageQuery            *PageQuery `protobuf:"bytes,99,opt,name=page_query,json=pageQuery,proto3" json:"page_query,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListBlueprintsRequest) Reset()         { *m = ListBlueprintsRequest{} }
func (m *ListBlueprintsRequest) String() string { return proto.CompactTextString(m) }
func (*ListBlueprintsRequest) ProtoMessage()    {}
func (*ListBlueprintsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d28a901b1212a72, []int{10}
}

func (m *ListBlueprintsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBlueprintsRequest.Unmarshal(m, b)
}
func (m *ListBlueprintsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBlueprintsRequest.Marshal(b, m, deterministic)
}
func (m *ListBlueprintsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBlueprintsRequest.Merge(m, src)
}
func (m *ListBlueprintsRequest) XXX_Size() int {
	return xxx_messageInfo_ListBlueprintsRequest.Size(m)
}
func (m *ListBlueprintsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBlueprintsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBlueprintsRequest proto.InternalMessageInfo

func (m *ListBlueprintsRequest) GetRepoQuery() *RepoQuery {
	if m != nil {
		return m.RepoQuery
	}
	return nil
}

func (m *ListBlueprintsRequest) GetPageQuery() *PageQuery {
	if m != nil {
		return m.PageQuery
	}
	return nil
}

type ListBlueprintsResponse struct {
	Blueprints           []*Blueprint `protobuf:"bytes,1,rep,name=blueprints,proto3" json:"blueprints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListBlueprintsResponse) Reset()         { *m = ListBlueprintsResponse{} }
func (m *ListBlueprintsResponse) String() string { return proto.CompactTextString(m) }
func (*ListBlueprintsResponse) ProtoMessage()    {}
func (*ListBlueprintsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d28a901b1212a72, []int{11}
}

func (m *ListBlueprintsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBlueprintsResponse.Unmarshal(m, b)
}
func (m *ListBlueprintsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBlueprintsResponse.Marshal(b, m, deterministic)
}
func (m *ListBlueprintsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBlueprintsResponse.Merge(m, src)
}
func (m *ListBlueprintsResponse) XXX_Size() int {
	return xxx_messageInfo_ListBlueprintsResponse.Size(m)
}
func (m *ListBlueprintsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBlueprintsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBlueprintsResponse proto.InternalMessageInfo

func (m *ListBlueprintsResponse) GetBlueprints() []*Blueprint {
	if m != nil {
		return m.Blueprints
	}
	return nil
}

type Build struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId            string               `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	HeadId               string               `protobuf:"bytes,3,opt,name=head_id,json=headId,proto3" json:"head_id,omitempty"`
	BlueprintId          string               `protobuf:"bytes,4,opt,name=blueprint_id,json=blueprintId,proto3" json:"blueprint_id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Build) Reset()         { *m = Build{} }
func (m *Build) String() string { return proto.CompactTextString(m) }
func (*Build) ProtoMessage()    {}
func (*Build) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d28a901b1212a72, []int{12}
}

func (m *Build) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Build.Unmarshal(m, b)
}
func (m *Build) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Build.Marshal(b, m, deterministic)
}
func (m *Build) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Build.Merge(m, src)
}
func (m *Build) XXX_Size() int {
	return xxx_messageInfo_Build.Size(m)
}
func (m *Build) XXX_DiscardUnknown() {
	xxx_messageInfo_Build.DiscardUnknown(m)
}

var xxx_messageInfo_Build proto.InternalMessageInfo

func (m *Build) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Build) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *Build) GetHeadId() string {
	if m != nil {
		return m.HeadId
	}
	return ""
}

func (m *Build) GetBlueprintId() string {
	if m != nil {
		return m.BlueprintId
	}
	return ""
}

func (m *Build) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Build) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type CreateBuildRequest struct {
	// The id of the project in the form of
	// `[PROJECT_ID]`.
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// The id of the head in the form of
	// `[HEAD_ID]`. Can be blank if building a commit with no head.
	HeadId string `protobuf:"bytes,2,opt,name=head_id,json=headId,proto3" json:"head_id,omitempty"`
	// The id of the blueprint in the form of
	// `[BLUEPRINT_ID]`.
	BlueprintId          string            `protobuf:"bytes,3,opt,name=blueprint_id,json=blueprintId,proto3" json:"blueprint_id,omitempty"`
	Parameters           map[string]string `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateBuildRequest) Reset()         { *m = CreateBuildRequest{} }
func (m *CreateBuildRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBuildRequest) ProtoMessage()    {}
func (*CreateBuildRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d28a901b1212a72, []int{13}
}

func (m *CreateBuildRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBuildRequest.Unmarshal(m, b)
}
func (m *CreateBuildRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBuildRequest.Marshal(b, m, deterministic)
}
func (m *CreateBuildRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBuildRequest.Merge(m, src)
}
func (m *CreateBuildRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBuildRequest.Size(m)
}
func (m *CreateBuildRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBuildRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBuildRequest proto.InternalMessageInfo

func (m *CreateBuildRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *CreateBuildRequest) GetHeadId() string {
	if m != nil {
		return m.HeadId
	}
	return ""
}

func (m *CreateBuildRequest) GetBlueprintId() string {
	if m != nil {
		return m.BlueprintId
	}
	return ""
}

func (m *CreateBuildRequest) GetParameters() map[string]string {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type GetBuildRequest struct {
	// The id of the project in the form of
	// `[PROJECT_ID]`.
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// The id of the build in the form of
	// `[BUILD_ID]`.
	BuildId              string   `protobuf:"bytes,2,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBuildRequest) Reset()         { *m = GetBuildRequest{} }
func (m *GetBuildRequest) String() string { return proto.CompactTextString(m) }
func (*GetBuildRequest) ProtoMessage()    {}
func (*GetBuildRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d28a901b1212a72, []int{14}
}

func (m *GetBuildRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBuildRequest.Unmarshal(m, b)
}
func (m *GetBuildRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBuildRequest.Marshal(b, m, deterministic)
}
func (m *GetBuildRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBuildRequest.Merge(m, src)
}
func (m *GetBuildRequest) XXX_Size() int {
	return xxx_messageInfo_GetBuildRequest.Size(m)
}
func (m *GetBuildRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBuildRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBuildRequest proto.InternalMessageInfo

func (m *GetBuildRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *GetBuildRequest) GetBuildId() string {
	if m != nil {
		return m.BuildId
	}
	return ""
}

type ListBuildsRequest struct {
	RepoQuery            *RepoQuery      `protobuf:"bytes,1,opt,name=repo_query,json=repoQuery,proto3" json:"repo_query,omitempty"`
	BlueprintQuery       *BlueprintQuery `protobuf:"bytes,2,opt,name=blueprint_query,json=blueprintQuery,proto3" json:"blueprint_query,omitempty"`
	PageQuery            *PageQuery      `protobuf:"bytes,99,opt,name=page_query,json=pageQuery,proto3" json:"page_query,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListBuildsRequest) Reset()         { *m = ListBuildsRequest{} }
func (m *ListBuildsRequest) String() string { return proto.CompactTextString(m) }
func (*ListBuildsRequest) ProtoMessage()    {}
func (*ListBuildsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d28a901b1212a72, []int{15}
}

func (m *ListBuildsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBuildsRequest.Unmarshal(m, b)
}
func (m *ListBuildsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBuildsRequest.Marshal(b, m, deterministic)
}
func (m *ListBuildsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBuildsRequest.Merge(m, src)
}
func (m *ListBuildsRequest) XXX_Size() int {
	return xxx_messageInfo_ListBuildsRequest.Size(m)
}
func (m *ListBuildsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBuildsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBuildsRequest proto.InternalMessageInfo

func (m *ListBuildsRequest) GetRepoQuery() *RepoQuery {
	if m != nil {
		return m.RepoQuery
	}
	return nil
}

func (m *ListBuildsRequest) GetBlueprintQuery() *BlueprintQuery {
	if m != nil {
		return m.BlueprintQuery
	}
	return nil
}

func (m *ListBuildsRequest) GetPageQuery() *PageQuery {
	if m != nil {
		return m.PageQuery
	}
	return nil
}

type ListBuildsResponse struct {
	Builds               []*Build `protobuf:"bytes,1,rep,name=builds,proto3" json:"builds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBuildsResponse) Reset()         { *m = ListBuildsResponse{} }
func (m *ListBuildsResponse) String() string { return proto.CompactTextString(m) }
func (*ListBuildsResponse) ProtoMessage()    {}
func (*ListBuildsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d28a901b1212a72, []int{16}
}

func (m *ListBuildsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBuildsResponse.Unmarshal(m, b)
}
func (m *ListBuildsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBuildsResponse.Marshal(b, m, deterministic)
}
func (m *ListBuildsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBuildsResponse.Merge(m, src)
}
func (m *ListBuildsResponse) XXX_Size() int {
	return xxx_messageInfo_ListBuildsResponse.Size(m)
}
func (m *ListBuildsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBuildsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBuildsResponse proto.InternalMessageInfo

func (m *ListBuildsResponse) GetBuilds() []*Build {
	if m != nil {
		return m.Builds
	}
	return nil
}

func init() {
	proto.RegisterEnum("velocity.v1.RepoQuery_RepoType", RepoQuery_RepoType_name, RepoQuery_RepoType_value)
	proto.RegisterType((*Project)(nil), "velocity.v1.Project")
	proto.RegisterType((*CreateProjectRequest)(nil), "velocity.v1.CreateProjectRequest")
	proto.RegisterType((*GetProjectRequest)(nil), "velocity.v1.GetProjectRequest")
	proto.RegisterType((*ListProjectsRequest)(nil), "velocity.v1.ListProjectsRequest")
	proto.RegisterType((*ListProjectsResponse)(nil), "velocity.v1.ListProjectsResponse")
	proto.RegisterType((*PageQuery)(nil), "velocity.v1.PageQuery")
	proto.RegisterType((*RepoQuery)(nil), "velocity.v1.RepoQuery")
	proto.RegisterType((*BlueprintQuery)(nil), "velocity.v1.BlueprintQuery")
	proto.RegisterType((*Blueprint)(nil), "velocity.v1.Blueprint")
	proto.RegisterType((*GetBlueprintRequest)(nil), "velocity.v1.GetBlueprintRequest")
	proto.RegisterType((*ListBlueprintsRequest)(nil), "velocity.v1.ListBlueprintsRequest")
	proto.RegisterType((*ListBlueprintsResponse)(nil), "velocity.v1.ListBlueprintsResponse")
	proto.RegisterType((*Build)(nil), "velocity.v1.Build")
	proto.RegisterType((*CreateBuildRequest)(nil), "velocity.v1.CreateBuildRequest")
	proto.RegisterMapType((map[string]string)(nil), "velocity.v1.CreateBuildRequest.ParametersEntry")
	proto.RegisterType((*GetBuildRequest)(nil), "velocity.v1.GetBuildRequest")
	proto.RegisterType((*ListBuildsRequest)(nil), "velocity.v1.ListBuildsRequest")
	proto.RegisterType((*ListBuildsResponse)(nil), "velocity.v1.ListBuildsResponse")
}

func init() { proto.RegisterFile("velocity.proto", fileDescriptor_9d28a901b1212a72) }

var fileDescriptor_9d28a901b1212a72 = []byte{
	// 982 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xdb, 0x6e, 0x1b, 0x45,
	0x18, 0x66, 0x37, 0x3e, 0xed, 0xef, 0xe0, 0xa4, 0x53, 0xb7, 0x59, 0xb6, 0x69, 0xe2, 0x0c, 0x05,
	0x45, 0x41, 0xf2, 0x12, 0xa3, 0x40, 0x89, 0x54, 0x41, 0xd2, 0x56, 0xad, 0x05, 0x55, 0xc3, 0x12,
	0x81, 0xc4, 0x4d, 0xb4, 0xf6, 0x0e, 0x66, 0xa8, 0xed, 0xdd, 0xee, 0x8e, 0x2d, 0x45, 0x88, 0x1b,
	0x10, 0xf7, 0x48, 0x3c, 0x0f, 0xd7, 0x3c, 0x00, 0xaf, 0xc0, 0x05, 0x6f, 0x01, 0x9a, 0xc3, 0x9e,
	0xbc, 0x6b, 0xa7, 0x4d, 0xaf, 0x76, 0x67, 0xe6, 0x3f, 0x7d, 0xdf, 0xff, 0xcf, 0x37, 0xd0, 0x9a,
	0x93, 0xb1, 0x3f, 0xa4, 0xec, 0xb2, 0x1b, 0x84, 0x3e, 0xf3, 0x51, 0x33, 0x59, 0xcf, 0x0f, 0xad,
	0xcd, 0x90, 0x04, 0x7e, 0x44, 0x99, 0x1f, 0xaa, 0x63, 0x6b, 0x77, 0xe4, 0xfb, 0xa3, 0x31, 0xb1,
	0xc5, 0x6a, 0x30, 0xfb, 0xde, 0x66, 0x74, 0x42, 0x22, 0xe6, 0x4e, 0x02, 0x65, 0xb0, 0xad, 0x0c,
	0xdc, 0x80, 0xda, 0xee, 0x74, 0xea, 0x33, 0x97, 0x51, 0x7f, 0x1a, 0xc9, 0x53, 0xfc, 0xa7, 0x06,
	0xf5, 0xb3, 0xd0, 0xff, 0x91, 0x0c, 0x19, 0x6a, 0x81, 0x4e, 0x3d, 0x53, 0xeb, 0x68, 0xfb, 0x86,
	0xa3, 0x53, 0x0f, 0x21, 0xa8, 0x4c, 0xdd, 0x09, 0x31, 0x75, 0xb1, 0x23, 0xfe, 0x91, 0x09, 0x75,
	0xd7, 0xf3, 0x42, 0x12, 0x45, 0xe6, 0x9a, 0xd8, 0x8e, 0x97, 0xe8, 0x53, 0x80, 0x61, 0x48, 0x5c,
	0x46, 0xbc, 0x0b, 0x97, 0x99, 0x95, 0x8e, 0xb6, 0xdf, 0xec, 0x59, 0x5d, 0x99, 0xbc, 0x1b, 0x57,
	0xd7, 0x3d, 0x8f, 0xab, 0x73, 0x0c, 0x65, 0x7d, 0xc2, 0xb8, 0xeb, 0x2c, 0xf0, 0x62, 0xd7, 0xea,
	0xd5, 0xae, 0xca, 0xfa, 0x84, 0xe1, 0x21, 0xb4, 0x1f, 0x8a, 0x38, 0x0a, 0x84, 0x43, 0x5e, 0xce,
	0x48, 0xc4, 0x92, 0xda, 0xb5, 0x4c, 0xed, 0x9f, 0x00, 0xa4, 0xf4, 0x09, 0x54, 0xcd, 0xde, 0x56,
	0x37, 0x43, 0x6f, 0xd7, 0x49, 0x8e, 0x9d, 0x8c, 0x29, 0xee, 0xc1, 0x8d, 0x27, 0x84, 0x2d, 0x64,
	0xb8, 0x0b, 0x10, 0xc8, 0x9d, 0x8b, 0x84, 0x35, 0x43, 0xed, 0xf4, 0x3d, 0xcc, 0xe0, 0xe6, 0x97,
	0x34, 0x8a, 0x9d, 0xa2, 0xd8, 0x6b, 0x13, 0xd6, 0xa8, 0x17, 0x99, 0x5a, 0x67, 0x6d, 0xdf, 0x70,
	0xf8, 0x2f, 0x6a, 0x43, 0x95, 0x57, 0x17, 0x99, 0xba, 0xd8, 0x93, 0x0b, 0x74, 0x04, 0x10, 0xb8,
	0x23, 0x72, 0xf1, 0x72, 0x46, 0xc2, 0x4b, 0x73, 0x28, 0x6a, 0xbd, 0x9d, 0xab, 0xf5, 0xcc, 0x1d,
	0x91, 0xaf, 0xf8, 0xa9, 0x63, 0x04, 0xf1, 0x2f, 0x7e, 0x0a, 0xed, 0x7c, 0xd6, 0x28, 0xf0, 0xa7,
	0x11, 0x41, 0x1f, 0x42, 0x43, 0x95, 0x26, 0x73, 0x37, 0x7b, 0xed, 0x7c, 0x30, 0x85, 0x2d, 0xb1,
	0xc2, 0x47, 0x60, 0x24, 0x19, 0x78, 0x8d, 0x63, 0x3a, 0xa1, 0x4c, 0xc0, 0xac, 0x3a, 0x72, 0xc1,
	0x39, 0x8e, 0x5e, 0xd0, 0x40, 0x30, 0x59, 0x75, 0xc4, 0x3f, 0xfe, 0x0c, 0x0c, 0x4e, 0xa2, 0x74,
	0x2b, 0x80, 0xc5, 0x1d, 0x68, 0xf0, 0xe3, 0xf3, 0xcb, 0x80, 0xa0, 0x06, 0x54, 0x9e, 0x3e, 0x3e,
	0x79, 0xb4, 0xf9, 0x16, 0x02, 0xa8, 0x3d, 0x7c, 0xfe, 0xec, 0x59, 0xff, 0x7c, 0x53, 0xc3, 0x18,
	0x5a, 0xa7, 0xe3, 0x19, 0x09, 0x42, 0x3a, 0x65, 0xcb, 0xa2, 0xdc, 0x07, 0x23, 0xb1, 0x29, 0x4c,
	0xed, 0x1d, 0x30, 0x86, 0xfe, 0x64, 0x42, 0x45, 0x5b, 0xe4, 0xe8, 0x36, 0xe4, 0x46, 0xdf, 0xc3,
	0xdf, 0xc2, 0xcd, 0x27, 0x84, 0x25, 0xce, 0xaf, 0xd6, 0x4b, 0xb4, 0x07, 0xeb, 0x83, 0xd8, 0x25,
	0x8d, 0xda, 0x4c, 0xf6, 0xfa, 0x1e, 0xfe, 0x4d, 0x83, 0x5b, 0x9c, 0xf9, 0x24, 0x74, 0xd2, 0xf1,
	0x23, 0x39, 0x75, 0xaa, 0x93, 0x5a, 0x49, 0x27, 0x13, 0xc2, 0x1c, 0x23, 0x4c, 0xb8, 0xbb, 0xe6,
	0x00, 0x9c, 0xc1, 0xed, 0xc5, 0x32, 0xd4, 0x08, 0x7c, 0x0c, 0x90, 0x14, 0x1c, 0x0f, 0x41, 0x3e,
	0x60, 0x4a, 0x4b, 0xc6, 0x12, 0xff, 0xab, 0x41, 0xf5, 0x74, 0x46, 0xc7, 0x5e, 0x81, 0xe9, 0x3c,
	0x6b, 0xfa, 0x22, 0x6b, 0x5b, 0x50, 0xff, 0x81, 0xb8, 0x1e, 0x3f, 0x93, 0x52, 0x51, 0xe3, 0xcb,
	0x12, 0x3a, 0x2b, 0x05, 0x3a, 0x17, 0xc4, 0xa4, 0x7a, 0x7d, 0x31, 0xa9, 0xbd, 0x8e, 0x98, 0xfc,
	0xa7, 0x01, 0x92, 0x6a, 0x22, 0x00, 0xbf, 0xe2, 0x74, 0x64, 0x70, 0xea, 0x2b, 0x71, 0xae, 0x15,
	0x71, 0x3e, 0xe7, 0x5d, 0x0e, 0xdd, 0x09, 0x61, 0x24, 0x8c, 0xcc, 0x8a, 0x68, 0x8a, 0x9d, 0x6b,
	0x4a, 0xb1, 0x9e, 0xee, 0x59, 0xe2, 0xf1, 0x78, 0xca, 0xb8, 0x54, 0xa5, 0x21, 0xac, 0x07, 0xb0,
	0xb1, 0x70, 0xcc, 0xef, 0xcf, 0x0b, 0x72, 0xa9, 0xea, 0xe6, 0xbf, 0xfc, 0x3a, 0xcf, 0xdd, 0xf1,
	0x2c, 0x56, 0x76, 0xb9, 0x38, 0xd6, 0xef, 0x6b, 0xf8, 0x0b, 0xd8, 0xe0, 0xf7, 0xe3, 0x35, 0xd0,
	0xbf, 0x03, 0x8d, 0x01, 0x37, 0x4f, 0xe1, 0xd7, 0xc5, 0xba, 0xef, 0xe1, 0xbf, 0x34, 0xb8, 0x21,
	0x86, 0x91, 0xaf, 0xdf, 0xf4, 0x3e, 0x3c, 0x82, 0x8d, 0x94, 0x4c, 0xe9, 0x2b, 0x15, 0xfc, 0x4e,
	0xf9, 0x0c, 0xcb, 0x00, 0xad, 0x41, 0x5e, 0x4b, 0xae, 0x79, 0xab, 0x3e, 0x07, 0x94, 0x05, 0xa2,
	0x6e, 0xd4, 0x01, 0xd4, 0x04, 0xd4, 0xf8, 0x36, 0xa1, 0x7c, 0x25, 0x82, 0x44, 0x65, 0xd1, 0xfb,
	0xbd, 0x0e, 0x1b, 0xdf, 0xa8, 0xd3, 0xaf, 0x49, 0x38, 0xa7, 0x43, 0x82, 0x46, 0xf0, 0x76, 0xee,
	0xed, 0x42, 0x7b, 0x25, 0x9d, 0xcf, 0xbf, 0x3a, 0x56, 0xa9, 0x6c, 0xe3, 0xbb, 0xbf, 0xfc, 0xfd,
	0xcf, 0x1f, 0xfa, 0x16, 0x5e, 0xb7, 0xe7, 0x87, 0x76, 0x2c, 0xe1, 0xc7, 0x75, 0xf5, 0x87, 0x5c,
	0x80, 0xf4, 0xfd, 0x42, 0x3b, 0xb9, 0x10, 0x85, 0x87, 0x6d, 0x75, 0x0a, 0x74, 0x8b, 0xa7, 0xf8,
	0x89, 0x3f, 0x52, 0x0f, 0xe2, 0x44, 0xf6, 0xc1, 0xcf, 0x88, 0xc2, 0x7a, 0xf6, 0xe1, 0x41, 0x9d,
	0x5c, 0x90, 0x92, 0x97, 0xd0, 0xda, 0x5b, 0x61, 0x21, 0x09, 0xc6, 0x6d, 0x91, 0xb3, 0x85, 0x72,
	0xb0, 0x10, 0x83, 0xf5, 0xac, 0x86, 0x2f, 0xa4, 0x2a, 0x91, 0x77, 0x6b, 0x89, 0xcc, 0xe1, 0x03,
	0x11, 0xff, 0x1e, 0xc2, 0x65, 0x98, 0xec, 0x54, 0x03, 0x39, 0xc0, 0x5f, 0x35, 0x68, 0xe5, 0x95,
	0x15, 0xe1, 0x02, 0x82, 0x82, 0xfa, 0x5b, 0xef, 0xae, 0xb4, 0x51, 0x38, 0xf7, 0x45, 0x1d, 0x18,
	0x75, 0x4a, 0xb9, 0xcd, 0x14, 0x82, 0x7c, 0x68, 0x66, 0x04, 0x01, 0xed, 0x5e, 0x21, 0x15, 0x56,
	0xc9, 0x48, 0xe2, 0x0f, 0x44, 0xb6, 0xf7, 0xf0, 0xf6, 0x92, 0x6c, 0x62, 0x60, 0x8f, 0xab, 0xe2,
	0x8b, 0x3c, 0x68, 0xc4, 0x82, 0x80, 0xb6, 0x0b, 0x44, 0x5f, 0x95, 0xea, 0x7d, 0x91, 0xaa, 0x83,
	0x76, 0xca, 0x09, 0x16, 0x99, 0x38, 0xb9, 0x11, 0x40, 0x7a, 0xbf, 0x16, 0x06, 0xb4, 0xa0, 0x20,
	0xd6, 0xee, 0xd2, 0x73, 0xc5, 0xe7, 0x3d, 0x91, 0x76, 0x07, 0xad, 0x44, 0x78, 0x5a, 0xf9, 0x4e,
	0x9f, 0x1f, 0x0e, 0x6a, 0xe2, 0x49, 0xf8, 0xe8, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa3, 0x32,
	0xcf, 0x45, 0x77, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VelocityServiceClient is the client API for VelocityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VelocityServiceClient interface {
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*Project, error)
	GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*Project, error)
	ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error)
	GetBlueprint(ctx context.Context, in *GetBlueprintRequest, opts ...grpc.CallOption) (*Blueprint, error)
	ListBlueprints(ctx context.Context, in *ListBlueprintsRequest, opts ...grpc.CallOption) (*ListBlueprintsResponse, error)
	CreateBuild(ctx context.Context, in *CreateBuildRequest, opts ...grpc.CallOption) (*Build, error)
	GetBuild(ctx context.Context, in *GetBuildRequest, opts ...grpc.CallOption) (*Build, error)
	ListBuilds(ctx context.Context, in *ListBuildsRequest, opts ...grpc.CallOption) (*ListBuildsResponse, error)
}

type velocityServiceClient struct {
	cc *grpc.ClientConn
}

func NewVelocityServiceClient(cc *grpc.ClientConn) VelocityServiceClient {
	return &velocityServiceClient{cc}
}

func (c *velocityServiceClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*Project, error) {
	out := new(Project)
	err := c.cc.Invoke(ctx, "/velocity.v1.VelocityService/CreateProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *velocityServiceClient) GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*Project, error) {
	out := new(Project)
	err := c.cc.Invoke(ctx, "/velocity.v1.VelocityService/GetProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *velocityServiceClient) ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error) {
	out := new(ListProjectsResponse)
	err := c.cc.Invoke(ctx, "/velocity.v1.VelocityService/ListProjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *velocityServiceClient) GetBlueprint(ctx context.Context, in *GetBlueprintRequest, opts ...grpc.CallOption) (*Blueprint, error) {
	out := new(Blueprint)
	err := c.cc.Invoke(ctx, "/velocity.v1.VelocityService/GetBlueprint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *velocityServiceClient) ListBlueprints(ctx context.Context, in *ListBlueprintsRequest, opts ...grpc.CallOption) (*ListBlueprintsResponse, error) {
	out := new(ListBlueprintsResponse)
	err := c.cc.Invoke(ctx, "/velocity.v1.VelocityService/ListBlueprints", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *velocityServiceClient) CreateBuild(ctx context.Context, in *CreateBuildRequest, opts ...grpc.CallOption) (*Build, error) {
	out := new(Build)
	err := c.cc.Invoke(ctx, "/velocity.v1.VelocityService/CreateBuild", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *velocityServiceClient) GetBuild(ctx context.Context, in *GetBuildRequest, opts ...grpc.CallOption) (*Build, error) {
	out := new(Build)
	err := c.cc.Invoke(ctx, "/velocity.v1.VelocityService/GetBuild", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *velocityServiceClient) ListBuilds(ctx context.Context, in *ListBuildsRequest, opts ...grpc.CallOption) (*ListBuildsResponse, error) {
	out := new(ListBuildsResponse)
	err := c.cc.Invoke(ctx, "/velocity.v1.VelocityService/ListBuilds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VelocityServiceServer is the server API for VelocityService service.
type VelocityServiceServer interface {
	CreateProject(context.Context, *CreateProjectRequest) (*Project, error)
	GetProject(context.Context, *GetProjectRequest) (*Project, error)
	ListProjects(context.Context, *ListProjectsRequest) (*ListProjectsResponse, error)
	GetBlueprint(context.Context, *GetBlueprintRequest) (*Blueprint, error)
	ListBlueprints(context.Context, *ListBlueprintsRequest) (*ListBlueprintsResponse, error)
	CreateBuild(context.Context, *CreateBuildRequest) (*Build, error)
	GetBuild(context.Context, *GetBuildRequest) (*Build, error)
	ListBuilds(context.Context, *ListBuildsRequest) (*ListBuildsResponse, error)
}

// UnimplementedVelocityServiceServer can be embedded to have forward compatible implementations.
type UnimplementedVelocityServiceServer struct {
}

func (*UnimplementedVelocityServiceServer) CreateProject(ctx context.Context, req *CreateProjectRequest) (*Project, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProject not implemented")
}
func (*UnimplementedVelocityServiceServer) GetProject(ctx context.Context, req *GetProjectRequest) (*Project, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProject not implemented")
}
func (*UnimplementedVelocityServiceServer) ListProjects(ctx context.Context, req *ListProjectsRequest) (*ListProjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProjects not implemented")
}
func (*UnimplementedVelocityServiceServer) GetBlueprint(ctx context.Context, req *GetBlueprintRequest) (*Blueprint, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlueprint not implemented")
}
func (*UnimplementedVelocityServiceServer) ListBlueprints(ctx context.Context, req *ListBlueprintsRequest) (*ListBlueprintsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBlueprints not implemented")
}
func (*UnimplementedVelocityServiceServer) CreateBuild(ctx context.Context, req *CreateBuildRequest) (*Build, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBuild not implemented")
}
func (*UnimplementedVelocityServiceServer) GetBuild(ctx context.Context, req *GetBuildRequest) (*Build, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBuild not implemented")
}
func (*UnimplementedVelocityServiceServer) ListBuilds(ctx context.Context, req *ListBuildsRequest) (*ListBuildsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBuilds not implemented")
}

func RegisterVelocityServiceServer(s *grpc.Server, srv VelocityServiceServer) {
	s.RegisterService(&_VelocityService_serviceDesc, srv)
}

func _VelocityService_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VelocityServiceServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/velocity.v1.VelocityService/CreateProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VelocityServiceServer).CreateProject(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VelocityService_GetProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VelocityServiceServer).GetProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/velocity.v1.VelocityService/GetProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VelocityServiceServer).GetProject(ctx, req.(*GetProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VelocityService_ListProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VelocityServiceServer).ListProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/velocity.v1.VelocityService/ListProjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VelocityServiceServer).ListProjects(ctx, req.(*ListProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VelocityService_GetBlueprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlueprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VelocityServiceServer).GetBlueprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/velocity.v1.VelocityService/GetBlueprint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VelocityServiceServer).GetBlueprint(ctx, req.(*GetBlueprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VelocityService_ListBlueprints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBlueprintsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VelocityServiceServer).ListBlueprints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/velocity.v1.VelocityService/ListBlueprints",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VelocityServiceServer).ListBlueprints(ctx, req.(*ListBlueprintsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VelocityService_CreateBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VelocityServiceServer).CreateBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/velocity.v1.VelocityService/CreateBuild",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VelocityServiceServer).CreateBuild(ctx, req.(*CreateBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VelocityService_GetBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VelocityServiceServer).GetBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/velocity.v1.VelocityService/GetBuild",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VelocityServiceServer).GetBuild(ctx, req.(*GetBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VelocityService_ListBuilds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBuildsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VelocityServiceServer).ListBuilds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/velocity.v1.VelocityService/ListBuilds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VelocityServiceServer).ListBuilds(ctx, req.(*ListBuildsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VelocityService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "velocity.v1.VelocityService",
	HandlerType: (*VelocityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProject",
			Handler:    _VelocityService_CreateProject_Handler,
		},
		{
			MethodName: "GetProject",
			Handler:    _VelocityService_GetProject_Handler,
		},
		{
			MethodName: "ListProjects",
			Handler:    _VelocityService_ListProjects_Handler,
		},
		{
			MethodName: "GetBlueprint",
			Handler:    _VelocityService_GetBlueprint_Handler,
		},
		{
			MethodName: "ListBlueprints",
			Handler:    _VelocityService_ListBlueprints_Handler,
		},
		{
			MethodName: "CreateBuild",
			Handler:    _VelocityService_CreateBuild_Handler,
		},
		{
			MethodName: "GetBuild",
			Handler:    _VelocityService_GetBuild_Handler,
		},
		{
			MethodName: "ListBuilds",
			Handler:    _VelocityService_ListBuilds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "velocity.proto",
}
