// Code generated by protoc-gen-go. DO NOT EDIT.
// source: velocity.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Project struct {
	// projects/<project_id>
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d28a901b1212a72, []int{0}
}

func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Blueprint struct {
	// projects/<project_id>/blueprints/<blueprint_id>
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// projects/<project_id>/commits/<commit_id>
	CommitId             string   `protobuf:"bytes,2,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blueprint) Reset()         { *m = Blueprint{} }
func (m *Blueprint) String() string { return proto.CompactTextString(m) }
func (*Blueprint) ProtoMessage()    {}
func (*Blueprint) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d28a901b1212a72, []int{1}
}

func (m *Blueprint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blueprint.Unmarshal(m, b)
}
func (m *Blueprint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blueprint.Marshal(b, m, deterministic)
}
func (m *Blueprint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blueprint.Merge(m, src)
}
func (m *Blueprint) XXX_Size() int {
	return xxx_messageInfo_Blueprint.Size(m)
}
func (m *Blueprint) XXX_DiscardUnknown() {
	xxx_messageInfo_Blueprint.DiscardUnknown(m)
}

var xxx_messageInfo_Blueprint proto.InternalMessageInfo

func (m *Blueprint) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Blueprint) GetCommitId() string {
	if m != nil {
		return m.CommitId
	}
	return ""
}

type CreateBuildRequest struct {
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	HeadId    string `protobuf:"bytes,2,opt,name=head_id,json=headId,proto3" json:"head_id,omitempty"`
	// building a commit with no head)
	CommitSha            string            `protobuf:"bytes,3,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	BlueprintName        string            `protobuf:"bytes,4,opt,name=blueprint_name,json=blueprintName,proto3" json:"blueprint_name,omitempty"`
	Parameters           map[string]string `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateBuildRequest) Reset()         { *m = CreateBuildRequest{} }
func (m *CreateBuildRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBuildRequest) ProtoMessage()    {}
func (*CreateBuildRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d28a901b1212a72, []int{2}
}

func (m *CreateBuildRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBuildRequest.Unmarshal(m, b)
}
func (m *CreateBuildRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBuildRequest.Marshal(b, m, deterministic)
}
func (m *CreateBuildRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBuildRequest.Merge(m, src)
}
func (m *CreateBuildRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBuildRequest.Size(m)
}
func (m *CreateBuildRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBuildRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBuildRequest proto.InternalMessageInfo

func (m *CreateBuildRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *CreateBuildRequest) GetHeadId() string {
	if m != nil {
		return m.HeadId
	}
	return ""
}

func (m *CreateBuildRequest) GetCommitSha() string {
	if m != nil {
		return m.CommitSha
	}
	return ""
}

func (m *CreateBuildRequest) GetBlueprintName() string {
	if m != nil {
		return m.BlueprintName
	}
	return ""
}

func (m *CreateBuildRequest) GetParameters() map[string]string {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type Build struct {
	// projects/<project_id>/builds/<build_id>
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// projects/<project_id>/blueprints/<blueprint_id>
	BlueprintId          string   `protobuf:"bytes,4,opt,name=blueprint_id,json=blueprintId,proto3" json:"blueprint_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Build) Reset()         { *m = Build{} }
func (m *Build) String() string { return proto.CompactTextString(m) }
func (*Build) ProtoMessage()    {}
func (*Build) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d28a901b1212a72, []int{3}
}

func (m *Build) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Build.Unmarshal(m, b)
}
func (m *Build) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Build.Marshal(b, m, deterministic)
}
func (m *Build) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Build.Merge(m, src)
}
func (m *Build) XXX_Size() int {
	return xxx_messageInfo_Build.Size(m)
}
func (m *Build) XXX_DiscardUnknown() {
	xxx_messageInfo_Build.DiscardUnknown(m)
}

var xxx_messageInfo_Build proto.InternalMessageInfo

func (m *Build) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Build) GetBlueprintId() string {
	if m != nil {
		return m.BlueprintId
	}
	return ""
}

func init() {
	proto.RegisterType((*Project)(nil), "velocity.v1.Project")
	proto.RegisterType((*Blueprint)(nil), "velocity.v1.Blueprint")
	proto.RegisterType((*CreateBuildRequest)(nil), "velocity.v1.CreateBuildRequest")
	proto.RegisterMapType((map[string]string)(nil), "velocity.v1.CreateBuildRequest.ParametersEntry")
	proto.RegisterType((*Build)(nil), "velocity.v1.Build")
}

func init() { proto.RegisterFile("velocity.proto", fileDescriptor_9d28a901b1212a72) }

var fileDescriptor_9d28a901b1212a72 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x4d, 0x4b, 0xfb, 0x40,
	0x10, 0xc6, 0xe9, 0xf6, 0xed, 0x9f, 0xe9, 0xdf, 0x56, 0x17, 0xc1, 0xa8, 0x08, 0x35, 0x20, 0xf4,
	0x14, 0x69, 0xbd, 0x94, 0x82, 0x97, 0x8a, 0x87, 0x5c, 0xb4, 0xb4, 0xe0, 0xc1, 0x4b, 0xd8, 0x66,
	0x07, 0xb2, 0x9a, 0x37, 0x37, 0x9b, 0x40, 0xbe, 0x8e, 0x9f, 0x54, 0x92, 0xac, 0x69, 0x31, 0xb7,
	0xcc, 0x6f, 0x32, 0xf3, 0x3c, 0xcf, 0x2c, 0x8c, 0x73, 0x0c, 0x62, 0x4f, 0xa8, 0xc2, 0x4e, 0x64,
	0xac, 0x62, 0x3a, 0x6a, 0xea, 0x7c, 0x6e, 0x5d, 0xc2, 0x70, 0x23, 0xe3, 0x0f, 0xf4, 0x14, 0x1d,
	0x03, 0x11, 0xdc, 0xec, 0x4c, 0x3b, 0x33, 0x63, 0x4b, 0x04, 0xb7, 0x96, 0x60, 0xac, 0x83, 0x0c,
	0x13, 0x29, 0xa2, 0x56, 0x93, 0x5e, 0x83, 0xe1, 0xc5, 0x61, 0x28, 0x94, 0x2b, 0xb8, 0x49, 0x2a,
	0xfc, 0xaf, 0x06, 0x0e, 0xb7, 0xbe, 0x09, 0xd0, 0x27, 0x89, 0x4c, 0xe1, 0x3a, 0x13, 0x01, 0xdf,
	0xe2, 0x57, 0x86, 0xa9, 0xa2, 0x37, 0x00, 0x49, 0xad, 0xe5, 0x36, 0xbb, 0x0c, 0x4d, 0x1c, 0x4e,
	0x2f, 0x60, 0xe8, 0x23, 0xe3, 0x87, 0x85, 0x83, 0xb2, 0x74, 0x78, 0x39, 0xa7, 0xb5, 0x52, 0x9f,
	0x99, 0xdd, 0x7a, 0xae, 0x26, 0x3b, 0x9f, 0xd1, 0x3b, 0x18, 0xef, 0x7f, 0x7d, 0xba, 0x11, 0x0b,
	0xd1, 0xec, 0x55, 0xbf, 0x9c, 0x34, 0xf4, 0x85, 0x85, 0x48, 0x5f, 0x01, 0x12, 0x26, 0x59, 0x88,
	0x0a, 0x65, 0x6a, 0xf6, 0xa7, 0xdd, 0xd9, 0x68, 0x71, 0x6f, 0x1f, 0xdd, 0xc2, 0x6e, 0x5b, 0xb6,
	0x37, 0xcd, 0xc4, 0x73, 0xa4, 0x64, 0xb1, 0x3d, 0x5a, 0x71, 0xf5, 0x08, 0x93, 0x3f, 0x6d, 0x7a,
	0x0a, 0xdd, 0x4f, 0x2c, 0x74, 0xb4, 0xf2, 0x93, 0x9e, 0x43, 0x3f, 0x67, 0x41, 0x86, 0x3a, 0x52,
	0x5d, 0xac, 0xc8, 0xb2, 0x63, 0xad, 0xa0, 0x5f, 0x49, 0xb5, 0x4e, 0x7b, 0x0b, 0xff, 0x0f, 0x79,
	0x04, 0xd7, 0x69, 0x46, 0x0d, 0x73, 0xf8, 0xe2, 0x0c, 0x26, 0x6f, 0xda, 0xf8, 0x0e, 0x65, 0x2e,
	0x3c, 0x5c, 0xf7, 0xde, 0x49, 0x3e, 0xdf, 0x0f, 0xaa, 0x27, 0x7e, 0xf8, 0x09, 0x00, 0x00, 0xff,
	0xff, 0x8a, 0xe4, 0xdc, 0xce, 0xf4, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VelocityServiceClient is the client API for VelocityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VelocityServiceClient interface {
}

type velocityServiceClient struct {
	cc *grpc.ClientConn
}

func NewVelocityServiceClient(cc *grpc.ClientConn) VelocityServiceClient {
	return &velocityServiceClient{cc}
}

// VelocityServiceServer is the server API for VelocityService service.
type VelocityServiceServer interface {
}

// UnimplementedVelocityServiceServer can be embedded to have forward compatible implementations.
type UnimplementedVelocityServiceServer struct {
}

func RegisterVelocityServiceServer(s *grpc.Server, srv VelocityServiceServer) {
	s.RegisterService(&_VelocityService_serviceDesc, srv)
}

var _VelocityService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "velocity.v1.VelocityService",
	HandlerType: (*VelocityServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "velocity.proto",
}
